import { GameItem, GlossaryTerm, Language, SearchableWasteItem, WasteType } from './types';

export const LANGUAGES: { id: Language; name: string; flag: string }[] = [
  { id: 'en', name: 'English', flag: '🇬🇧' },
  { id: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { id: 'zh', name: '中文', flag: '🇨🇳' },
];

// All translation keys must be in the 'en' object.
// Other languages will fallback to 'en' if a key is missing.
export const TRANSLATIONS = {
    en: {
        // App
        appTitle: 'Waste Wizard',
        chatTab: 'Chat Wizard',
        gameTab: 'Sort Game',
        infoTab: 'Info & Search',
        footer: 'Waste Wizard © 2024 - Learn to sort waste correctly!',

        // Header
        // (no specific keys here)

        // Chat Agent
        chatIntro: "Hello! I'm the Waste Wizard. Ask me anything about waste separation in the Netherlands, for example: 'Where does a milk carton go?' or 'What are the rules for plastic in Amsterdam?'",
        chatPlaceholder: 'Ask the wizard a question...',
        sources: 'Sources',

        // Game
        gameTitle: 'Waste Sorting Game',
        gameIntro: 'Drag the item to the correct bin!',
        score: 'Score',
        finalScore: 'Final Score',
        playAgain: 'Play Again',
        enterNickname: 'Enter your nickname...',
        saveScore: 'Save Score',
        highScores: 'High Scores',
        gameCorrectBinMessage: 'Correct! This goes in the {binName} bin.',

        // Info & Glossary
        infoTitle: 'Useful Information',
        infoIntro: 'Find more information about waste separation at these official sources.',
        gemeenteContact: 'Your Municipality (Gemeente)',
        gemeenteDesc: 'Rules can differ per city. Always check your local municipality website for the most accurate information.',
        milieuCentraal: 'Milieu Centraal',
        milieuCentraalDesc: 'An independent organization with practical information on sustainability and energy.',
        afvalscheidingswijzer: 'Afvalscheidingswijzer',
        afvalscheidingswijzerDesc: 'The official guide for waste separation in the Netherlands.',
        glossaryTitle: 'Glossary of Waste Types',

        // Waste Search
        wasteSearchTitle: 'What goes where?',
        wasteSearchPlaceholder: 'Search for a waste item...',
        wasteTypeResult: 'Goes in:',

        // Waste Types (for bins and glossary)
        gft: 'VGF (Vegetable, Garden & Fruit)',
        pmd: 'PMD (Plastic, Metal & Drink cartons)',
        rest: 'Residual Waste',
        papier: 'Paper & Cardboard',
        glas: 'Glass',
        kca: 'Small Chemical Waste',
        textiel: 'Textiles',
        'e-waste': 'E-Waste',
        grofvuil: 'Bulky Waste',

        // Waste type definitions (glossary)
        gft_def: 'For all your organic waste like fruit and vegetable scraps, food leftovers, and small garden waste.',
        pmd_def: 'For plastic packaging (bottles, containers), metal packaging (cans), and drink cartons (milk, juice).',
        rest_def: 'For all waste that cannot be separated into other categories, such as diapers or chip bags.',
        papier_def: 'For clean and dry paper and cardboard, like newspapers, boxes, and envelopes.',
        glas_def: 'For empty glass bottles and jars. Lids can often go in PMD. Check local rules.',
        kca_def: 'For hazardous waste like batteries, paint, and energy-saving lamps. Must be returned to a special collection point.',
        textiel_def: 'For wearable clothing, shoes, towels, and home textiles. Should be clean and dry, delivered in a closed bag to a textile container.',
        'e-waste_def': 'For all devices with a plug or battery. Return small devices to stores or bring them to a recycling center (milieustraat).',
        grofvuil_def: 'For large items that do not fit in the regular bin, like furniture. Arrange for collection with your municipality or bring it to a recycling center.',

        // Game items
        apple_core: 'Apple Core',
        plastic_bottle: 'Plastic Bottle',
        pizza_box: 'Greasy Pizza Box',
        newspaper: 'Newspaper',
        wine_bottle: 'Wine Bottle',
        battery: 'Battery',
        banana_peel: 'Banana Peel',
        milk_carton: 'Milk Carton',
        chips_bag: 'Chips Bag',
        cardboard_box: 'Cardboard Box',
        jar_of_jam: 'Jam Jar',
        paint_can: 'Paint Can',
        coffee_grounds: 'Coffee Grounds',
        yoghurt_cup: 'Yoghurt Cup',
        light_bulb: 'Incandescent Bulb',
        magazine: 'Magazine',
        old_tshirt: 'Old T-shirt',
        broken_phone: 'Broken Phone',
    },
    nl: {
        // App
        appTitle: 'Afval Wizard',
        chatTab: 'Chat Wizard',
        gameTab: 'Sorteer Spel',
        infoTab: 'Info & Zoeken',
        footer: 'Afval Wizard © 2024 - Leer afval correct te scheiden!',

        // Chat Agent
        chatIntro: "Hallo! Ik ben de Afval Wizard. Stel me een vraag over afvalscheiding in Nederland, bijvoorbeeld: 'Waar hoort een melkpak?' of 'Wat zijn de regels voor plastic in Amsterdam?'",
        chatPlaceholder: 'Stel de wizard een vraag...',
        sources: 'Bronnen',

        // Game
        gameTitle: 'Afval Sorteer Spel',
        gameIntro: 'Sleep het voorwerp naar de juiste bak!',
        score: 'Score',
        finalScore: 'Eindscore',
        playAgain: 'Opnieuw Spelen',
        enterNickname: 'Voer je bijnaam in...',
        saveScore: 'Score Opslaan',
        highScores: 'Highscores',
        gameCorrectBinMessage: 'Correct! Dit hoort in de {binName} bak.',

        // Info & Glossary
        infoTitle: 'Nuttige Informatie',
        infoIntro: 'Vind meer informatie over afvalscheiding bij deze officiële bronnen.',
        gemeenteContact: 'Jouw Gemeente',
        gemeenteDesc: 'Regels kunnen per stad verschillen. Controleer altijd de website van je lokale gemeente voor de meest accurate informatie.',
        milieuCentraal: 'Milieu Centraal',
        milieuCentraalDesc: 'Een onafhankelijke organisatie met praktische informatie over duurzaamheid en energie.',
        afvalscheidingswijzer: 'Afvalscheidingswijzer',
        afvalscheidingswijzerDesc: 'De officiële gids voor afvalscheiding in Nederland.',
        glossaryTitle: 'Woordenlijst Afvalsoorten',

        // Waste Search
        wasteSearchTitle: 'Wat hoort waar?',
        wasteSearchPlaceholder: 'Zoek naar een afvalproduct...',
        wasteTypeResult: 'Hoort in:',

        // Waste Types
        gft: 'GFT (Groente-, Fruit- en Tuinafval)',
        pmd: 'PMD (Plastic, Metaal & Drankkartons)',
        rest: 'Restafval',
        papier: 'Papier & Karton',
        glas: 'Glas',
        kca: 'Klein Chemisch Afval',
        textiel: 'Textiel',
        'e-waste': 'Elektrisch Afval',
        grofvuil: 'Grofvuil',

        // Waste type definitions
        gft_def: 'Voor al je organisch afval zoals groente- en fruitschillen, etensresten en klein tuinafval.',
        pmd_def: 'Voor plastic verpakkingen (flessen, bakjes), metalen verpakkingen (blikjes) en drankkartons (melk, sap).',
        rest_def: 'Voor al het afval dat niet in andere categorieën kan worden gescheiden, zoals luiers of chipszakken.',
        papier_def: 'Voor schoon en droog papier en karton, zoals kranten, dozen en enveloppen.',
        glas_def: 'Voor lege glazen flessen en potten. Deksels mogen vaak bij PMD. Controleer lokale regels.',
        kca_def: 'Voor gevaarlijk afval zoals batterijen, verf en spaarlampen. Moet worden ingeleverd bij een speciaal inzamelpunt.',
        textiel_def: 'Voor draagbare kleding, schoenen, handdoeken en huishoudtextiel. Moet schoon en droog zijn, aangeleverd in een gesloten zak bij een textielcontainer.',
        'e-waste_def': 'Voor alle apparaten met een stekker of batterij. Lever kleine apparaten in bij winkels of breng ze naar een milieustraat.',
        grofvuil_def: 'Voor grote spullen die niet in de gewone container passen, zoals meubels. Maak een afspraak voor ophaling met je gemeente of breng het naar een milieustraat.',

        // Game items
        apple_core: 'Klokhuis',
        plastic_bottle: 'Plastic Fles',
        pizza_box: 'Vette Pizzadoos',
        newspaper: 'Krant',
        wine_bottle: 'Wijnfles',
        battery: 'Batterij',
        banana_peel: 'Bananenschil',
        milk_carton: 'Melkpak',
        chips_bag: 'Chipszak',
        cardboard_box: 'Kartonnen Doos',
        jar_of_jam: 'Jampot',
        paint_can: 'Verfblik',
        coffee_grounds: 'Koffiedik',
        yoghurt_cup: 'Yoghurtbeker',
        light_bulb: 'Gloeilamp',
        magazine: 'Tijdschrift',
        old_tshirt: 'Oud T-shirt',
        kapotte_telefoon: 'Kapotte Telefoon',
    },
    zh: {
        // App
        appTitle: '垃圾分类精灵',
        chatTab: '聊天精灵',
        gameTab: '分类游戏',
        infoTab: '信息与搜索',
        footer: '垃圾分类精灵 © 2024 - 学习正确分类垃圾！',

        // Chat Agent
        chatIntro: "你好！我是垃圾分类精灵。你可以问我任何关于荷兰垃圾分类的问题，例如：'牛奶盒应该扔在哪里？' 或 '阿姆斯特丹对塑料有什么规定？'",
        chatPlaceholder: '向精灵提问...',
        sources: '来源',

        // Game
        gameTitle: '垃圾分类游戏',
        gameIntro: '将物品拖到正确的垃圾箱！',
        score: '分数',
        finalScore: '最终得分',
        playAgain: '再玩一次',
        enterNickname: '输入你的昵称...',
        saveScore: '保存分数',
        highScores: '高分榜',
        gameCorrectBinMessage: '正确！这应该扔进 {binName} 箱。',

        // Info & Glossary
        infoTitle: '有用信息',
        infoIntro: '在这些官方来源找到更多关于垃圾分类的信息。',
        gemeenteContact: '你所在的市政府 (Gemeente)',
        gemeenteDesc: '不同城市的规定可能不同。请务必查看你当地市政府的网站以获取最准确的信息。',
        milieuCentraal: '中央环境',
        milieuCentraalDesc: '一个提供关于可持续性和能源实用信息的独立组织。',
        afvalscheidingswijzer: '垃圾分类指南',
        afvalscheidingswijzerDesc: '荷兰官方的垃圾分类指南。',
        glossaryTitle: '垃圾类型词汇表',
        
        // Waste Search
        wasteSearchTitle: '什么东西扔哪里？',
        wasteSearchPlaceholder: '搜索垃圾物品...',
        wasteTypeResult: '扔进：',

        // Waste Types
        gft: 'VGF (蔬菜、花园和水果垃圾)',
        pmd: 'PMD (塑料、金属和饮料纸盒)',
        rest: '残余垃圾',
        papier: '纸张和纸板',
        glas: '玻璃',
        kca: '小型化学废物',
        textiel: '纺织品',
        'e-waste': '电子垃圾',
        grofvuil: '大件垃圾',

        // Waste type definitions
        gft_def: '适用于所有有机废物，如水果和蔬菜皮、食物残渣和小型花园废物。',
        pmd_def: '适用于塑料包装（瓶子、容器）、金属包装（罐头）和饮料纸盒（牛奶、果汁）。',
        rest_def: '适用于所有不能分类到其他类别的垃圾，如尿布或薯片袋。',
        papier_def: '适用于清洁干燥的纸张和纸板，如报纸、盒子和信封。',
        glas_def: '适用于空的玻璃瓶和罐子。盖子通常可以放入PMD。请检查当地规定。',
        kca_def: '适用于有害废物，如电池、油漆和节能灯。必须交回特殊收集点。',
        textiel_def: '适用于可穿戴的衣物、鞋子、毛巾和家用纺织品。应保持清洁干燥，并放入封闭的袋子中，投放到纺织品回收箱。',
        'e-waste_def': '适用于所有带插头或电池的设备。将小型设备退回商店或带到回收中心 (milieustraat)。',
        grofvuil_def: '适用于无法放入普通垃圾箱的大件物品，如家具。请与你所在的市政府安排收集，或将其带到回收中心。',

        // Game items
        apple_core: '苹果核',
        plastic_bottle: '塑料瓶',
        pizza_box: '油腻的披萨盒',
        newspaper: '报纸',
        wine_bottle: '酒瓶',
        battery: '电池',
        banana_peel: '香蕉皮',
        milk_carton: '牛奶盒',
        chips_bag: '薯片袋',
        cardboard_box: '纸板箱',
        jar_of_jam: '果酱罐',
        paint_can: '油漆罐',
        coffee_grounds: '咖啡渣',
        yoghurt_cup: '酸奶杯',
        light_bulb: '白炽灯泡',
        magazine: '杂志',
        old_tshirt: '旧T恤',
        broken_phone: '坏掉的手机',
    },
};

export const WASTE_BINS: Record<WasteType, { nameKey: keyof typeof TRANSLATIONS['en']; color: string; }> = {
    gft: { nameKey: 'gft', color: 'bg-green-500' },
    pmd: { nameKey: 'pmd', color: 'bg-orange-400' },
    rest: { nameKey: 'rest', color: 'bg-gray-500' },
    papier: { nameKey: 'papier', color: 'bg-blue-500' },
    glas: { nameKey: 'glas', color: 'bg-yellow-400' },
    kca: { nameKey: 'kca', color: 'bg-red-600' },
    textiel: { nameKey: 'textiel', color: 'bg-purple-500' },
    'e-waste': { nameKey: 'e-waste', color: 'bg-slate-700' },
    grofvuil: { nameKey: 'grofvuil', color: 'bg-amber-800' },
};

export const WASTE_ITEMS: GameItem[] = [
    { nameKey: 'apple_core', image: 'https://i.imgur.com/vL3zQY8.png', type: 'gft' },
    { nameKey: 'plastic_bottle', image: 'https://i.imgur.com/d3aA8Y6.png', type: 'pmd' },
    { nameKey: 'pizza_box', image: 'https://i.imgur.com/uEVvT9H.png', type: 'rest' },
    { nameKey: 'newspaper', image: 'https://i.imgur.com/3Y1ZgQ1.png', type: 'papier' },
    { nameKey: 'wine_bottle', image: 'https://i.imgur.com/4zY4J9p.png', type: 'glas' },
    { nameKey: 'battery', image: 'https://i.imgur.com/9O1yY8T.png', type: 'kca' },
    { nameKey: 'banana_peel', image: 'https://i.imgur.com/J3s0U0S.png', type: 'gft' },
    { nameKey: 'milk_carton', image: 'https://i.imgur.com/Dq8g5g9.png', type: 'pmd' },
    { nameKey: 'chips_bag', image: 'https://i.imgur.com/i8z6o9o.png', type: 'rest' },
    { nameKey: 'cardboard_box', image: 'https://i.imgur.com/mU1gR1j.png', type: 'papier' },
    { nameKey: 'jar_of_jam', image: 'https://i.imgur.com/o3V8aY0.png', type: 'glas' },
    { nameKey: 'paint_can', image: 'https://i.imgur.com/Y1gQ9jT.png', type: 'kca' },
    { nameKey: 'coffee_grounds', image: 'https://i.imgur.com/7b3b8g6.png', type: 'gft' },
    { nameKey: 'yoghurt_cup', image: 'https://i.imgur.com/2Y4bS2s.png', type: 'pmd' },
    { nameKey: 'light_bulb', image: 'https://i.imgur.com/e3g3u4X.png', type: 'rest' },
    { nameKey: 'magazine', image: 'https://i.imgur.com/0u0bV1X.png', type: 'papier' },
    { nameKey: 'old_tshirt', image: 'https://i.imgur.com/Q3H2R9s.png', type: 'textiel' },
    { nameKey: 'broken_phone', image: 'https://i.imgur.com/6U8Y2kY.png', type: 'e-waste' },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
    { termKey: 'gft', definitionKey: 'gft_def' },
    { termKey: 'pmd', definitionKey: 'pmd_def' },
    { termKey: 'rest', definitionKey: 'rest_def' },
    { termKey: 'papier', definitionKey: 'papier_def' },
    { termKey: 'glas', definitionKey: 'glas_def' },
    { termKey: 'kca', definitionKey: 'kca_def' },
    { termKey: 'textiel', definitionKey: 'textiel_def' },
    { termKey: 'e-waste', definitionKey: 'e-waste_def' },
    { termKey: 'grofvuil', definitionKey: 'grofvuil_def' },
];

// Massively expanded list based on afvalscheidingswijzer.nl
const wasteList: SearchableWasteItem[] = [
  // E-Waste
  { type: 'e-waste', en: 'Adapter', nl: 'Adapter', zh: '适配器' },
  { type: 'e-waste', en: 'Blender', nl: 'Blender', zh: '搅拌机' },
  { type: 'e-waste', en: 'Coffee maker', nl: 'Koffiezetapparaat', zh: '咖啡机' },
  { type: 'e-waste', en: 'Computer', nl: 'Computer', zh: '电脑' },
  { type: 'e-waste', en: 'DVD player', nl: 'Dvd-speler', zh: 'DVD播放机' },
  { type: 'e-waste', en: 'Electric toothbrush', nl: 'Elektrische tandenborstel', zh: '电动牙刷' },
  { type: 'e-waste', en: 'Game console', nl: 'Spelcomputer', zh: '游戏机' },
  { type: 'e-waste', en: 'Hairdryer', nl: 'Föhn', zh: '吹风机' },
  { type: 'e-waste', en: 'Iron', nl: 'Strijkijzer', zh: '熨斗' },
  { type: 'e-waste', en: 'Kettle', nl: 'Waterkoker', zh: '电水壶' },
  { type: 'e-waste', en: 'Keyboard', nl: 'Toetsenbord', zh: '键盘' },
  { type: 'e-waste', en: 'Laptop', nl: 'Laptop', zh: '笔记本电脑' },
  { type: 'e-waste', en: 'Microwave', nl: 'Magnetron', zh: '微波炉' },
  { type: 'e-waste', en: 'Mobile phone', nl: 'Mobiele telefoon', zh: '手机' },
  { type: 'e-waste', en: 'Monitor', nl: 'Monitor', zh: '显示器' },
  { type: 'e-waste', en: 'Mouse', nl: 'Muis', zh: '鼠标' },
  { type: 'e-waste', en: 'Printer', nl: 'Printer', zh: '打印机' },
  { type: 'e-waste', en: 'Remote control', nl: 'Afstandsbediening', zh: '遥控器' },
  { type: 'e-waste', en: 'Shaver', nl: 'Scheerapparaat', zh: '剃须刀' },
  { type: 'e-waste', en: 'Tablet', nl: 'Tablet', zh: '平板电脑' },
  { type: 'e-waste', en: 'Television', nl: 'Televisie', zh: '电视机' },
  { type: 'e-waste', en: 'Toaster', nl: 'Broodrooster', zh: '烤面包机' },
  { type: 'e-waste', en: 'USB stick', nl: 'USB-stick', zh: 'U盘' },
  { type: 'e-waste', en: 'Vacuum cleaner', nl: 'Stofzuiger', zh: '吸尘器' },
  
  // GFT
  { type: 'gft', en: 'Animal food leftovers', nl: 'Dierenvoeding resten', zh: '动物食物残渣' },
  { type: 'gft', en: 'Apple core', nl: 'Klokhuis', zh: '苹果核' },
  { type: 'gft', en: 'Banana peel', nl: 'Bananenschil', zh: '香蕉皮' },
  { type: 'gft', en: 'Bones and fish bones', nl: 'Botten en graten', zh: '骨头和鱼刺' },
  { type: 'gft', en: 'Bread', nl: 'Brood', zh: '面包' },
  { type: 'gft', en: 'Cheese rind (natural)', nl: 'Kaaskorst (natuurlijk)', zh: '奶酪皮（天然）' },
  { type: 'gft', en: 'Coffee grounds', nl: 'Koffiedik', zh: '咖啡渣' },
  { type: 'gft', en: 'Coffee filter', nl: 'Koffiefilter', zh: '咖啡滤纸' },
  { type: 'gft', en: 'Egg shells', nl: 'Eierschalen', zh: '蛋壳' },
  { type: 'gft', en: 'Flowers', nl: 'Bloemen', zh: '花卉' },
  { type: 'gft', en: 'Food leftovers (cooked)', nl: 'Etensresten (gekookt)', zh: '剩菜（熟）' },
  { type: 'gft', en: 'Grass clippings', nl: 'Gras', zh: '草屑' },
  { type: 'gft', en: 'Hair (human and animal)', nl: 'Haar (mens en dier)', zh: '毛发（人和动物）' },
  { type: 'gft', en: 'Leaves', nl: 'Bladeren', zh: '树叶' },
  { type: 'gft', en: 'Matchstick', nl: 'Lucifer', zh: '火柴' },
  { type: 'gft', en: 'Nutshells', nl: 'Notendoppen', zh: '坚果壳' },
  { type: 'gft', en: 'Plants (indoor)', nl: 'Kamerplanten', zh: '室内植物' },
  { type: 'gft', en: 'Potato peels', nl: 'Aardappelschillen', zh: '土豆皮' },
  { type: 'gft', en: 'Tea bag', nl: 'Theezakje', zh: '茶包' },
  { type: 'gft', en: 'Vegetable scraps', nl: 'Groenteafval', zh: '蔬菜屑' },
  { type: 'gft', en: 'Weeds', nl: 'Onkruid', zh: '杂草' },
  
  // Glass
  { type: 'glas', en: 'Beer bottle', nl: 'Bierflesje', zh: '啤酒瓶' },
  { type: 'glas', en: 'Cosmetics jar (glass)', nl: 'Cosmeticapotje (glas)', zh: '化妆品罐（玻璃）' },
  { type: 'glas', en: 'Deodorant roller (glass)', nl: 'Deoroller (glas)', zh: '止汗滚珠（玻璃）' },
  { type: 'glas', en: 'Jar of jam', nl: 'Jampot', zh: '果酱罐' },
  { type: 'glas', en: 'Olive oil bottle', nl: 'Olijfoliefles', zh: '橄榄油瓶' },
  { type: 'glas', en: 'Perfume bottle', nl: 'Parfumflesje', zh: '香水瓶' },
  { type: 'glas', en: 'Sauce bottle (glass)', nl: 'Sausfles (glas)', zh: '酱料瓶（玻璃）' },
  { type: 'glas', en: 'Wine bottle', nl: 'Wijnfles', zh: '酒瓶' },

  // Bulky Waste (Grofvuil)
  { type: 'grofvuil', en: 'Bicycle', nl: 'Fiets', zh: '自行车' },
  { type: 'grofvuil', en: 'Carpet', nl: 'Tapijt', zh: '地毯' },
  { type: 'grofvuil', en: 'Chair', nl: 'Stoel', zh: '椅子' },
  { type: 'grofvuil', en: 'Closet', nl: 'Kast', zh: '衣柜' },
  { type: 'grofvuil', en: 'Laminate flooring', nl: 'Laminaat', zh: '复合地板' },
  { type: 'grofvuil', en: 'Mattress', nl: 'Matras', zh: '床垫' },
  { type: 'grofvuil', en: 'Mirror', nl: 'Spiegel', zh: '镜子' },
  { type: 'grofvuil', en: 'Planks', nl: 'Planken', zh: '木板' },
  { type: 'grofvuil', en: 'Rubble', nl: 'Puin', zh: '瓦砾' },
  { type: 'grofvuil', en: 'Sofa', nl: 'Bankstel', zh: '沙发' },
  { type: 'grofvuil', en: 'Styrofoam (large, clean)', nl: 'Piepschuim (groot, schoon)', zh: '泡沫塑料（大块、干净）' },
  { type: 'grofvuil', en: 'Table', nl: 'Tafel', zh: '桌子' },
  { type: 'grofvuil', en: 'Tire', nl: 'Autoband', zh: '轮胎' },
  { type: 'grofvuil', en: 'Wood', nl: 'Hout', zh: '木材' },

  // KCA
  { type: 'kca', en: 'Aerosol can (not empty)', nl: 'Spuitbus (niet leeg)', zh: '气雾罐（未空）' },
  { type: 'kca', en: 'Battery', nl: 'Batterij', zh: '电池' },
  { type: 'kca', en: 'Energy-saving lamp', nl: 'Spaarlamp', zh: '节能灯' },
  { type: 'kca', en: 'Fluorescent tube', nl: 'Tl-buis', zh: '荧光灯管' },
  { type: 'kca', en: 'Frying oil', nl: 'Frituurvet', zh: '煎炸油' },
  { type: 'kca', en: 'LED lamp', nl: 'Ledlamp', zh: 'LED灯' },
  { type: 'kca', en: 'Lighter', nl: 'Aansteker', zh: '打火机' },
  { type: 'kca', en: 'Medicine', nl: 'Medicijnen', zh: '药品' },
  { type: 'kca', en: 'Nail polish', nl: 'Nagellak', zh: '指甲油' },
  { type: 'kca', en: 'Paint can', nl: 'Verfblik', zh: '油漆罐' },
  { type: 'kca', en: 'Pesticides', nl: 'Bestrijdingsmiddelen', zh: '杀虫剂' },
  { type: 'kca', en: 'Syringe', nl: 'Injectienaald', zh: '注射器' },
  { type: 'kca', en: 'Thermometer (mercury)', nl: 'Kwikthermometer', zh: '水银温度计' },

  // Paper
  { type: 'papier', en: 'Book', nl: 'Boek', zh: '书' },
  { type: 'papier', en: 'Cardboard box', nl: 'Kartonnen doos', zh: '纸板箱' },
  { type: 'papier', en: 'Egg carton', nl: 'Eierdoos', zh: '鸡蛋盒' },
  { type: 'papier', en: 'Envelope', nl: 'Envelop', zh: '信封' },
  { type: 'papier', en: 'Envelope (with window)', nl: 'Envelop met venster', zh: '开窗信封' },
  { type: 'papier', en: 'Gift wrap', nl: 'Cadeaupapier', zh: '礼品包装纸' },
  { type: 'papier', en: 'Magazine', nl: 'Tijdschrift', zh: '杂志' },
  { type: 'papier', en: 'Newspaper', nl: 'Krant', zh: '报纸' },
  { type: 'papier', en: 'Office paper', nl: 'Kantoorpapier', zh: '办公用纸' },
  { type: 'papier', en: 'Toilet paper roll', nl: 'Wc-rolletje', zh: '卫生纸卷筒' },
  { type: 'papier', en: 'Wrapping paper', nl: 'Inpakpapier', zh: '包装纸' },

  // PMD
  { type: 'pmd', en: 'Aerosol can (empty)', nl: 'Spuitbus (leeg)', zh: '气雾罐（空）' },
  { type: 'pmd', en: 'Aluminum foil', nl: 'Aluminiumfolie', zh: '铝箔' },
  { type: 'pmd', en: 'Aluminum container', nl: 'Aluminium bakje', zh: '铝制容器' },
  { type: 'pmd', en: 'Blister pack (empty)', nl: 'Lege doordrukstrip', zh: '空泡罩包装' },
  { type: 'pmd', en: 'Bottle cap (metal)', nl: 'Kroonkurk', zh: '瓶盖（金属）' },
  { type: 'pmd', en: 'Can (soda)', nl: 'Blikje (frisdrank)', zh: '易拉罐（汽水）' },
  { type: 'pmd', en: 'Deodorant can (empty)', nl: 'Deodorant spuitbus (leeg)', zh: '除臭喷雾罐（空）' },
  { type: 'pmd', en: 'Flower pot (plastic)', nl: 'Bloempot (plastic)', zh: '花盆（塑料）' },
  { type: 'pmd', en: 'Lid (metal)', nl: 'Deksel (metaal)', zh: '盖子（金属）' },
  { type: 'pmd', en: 'Milk carton', nl: 'Melkpak', zh: '牛奶盒' },
  { type: 'pmd', en: 'Plastic bag', nl: 'Plastic tas', zh: '塑料袋' },
  { type: 'pmd', en: 'Plastic bottle', nl: 'Plastic fles', zh: '塑料瓶' },
  { type: 'pmd', en: 'Plastic container', nl: 'Plastic bakje', zh: '塑料容器' },
  { type: 'pmd', en: 'Plastic wrap', nl: 'Plasticfolie', zh: '保鲜膜' },
  { type: 'pmd', en: 'Shampoo bottle', nl: 'Shampoofles', zh: '洗发水瓶' },
  { type: 'pmd', en: 'Tetra pak', nl: 'Drankkarton', zh: '利乐包' },
  { type: 'pmd', en: 'Tin can', nl: 'Conservenblik', zh: '罐头' },
  { type: 'pmd', en: 'Yoghurt cup', nl: 'Yoghurtbeker', zh: '酸奶杯' },
  
  // Residual Waste
  { type: 'rest', en: 'Ash', nl: 'As', zh: '灰烬' },
  { type: 'rest', en: 'Baking paper', nl: 'Bakpapier', zh: '烘焙纸' },
  { type: 'rest', en: 'Balloon', nl: 'Ballon', zh: '气球' },
  { type: 'rest', en: 'Band-aid', nl: 'Pleister', zh: '创可贴' },
  { type: 'rest', en: 'Bird cage sand', nl: 'Vogelkooizand', zh: '鸟笼沙' },
  { type: 'rest', en: 'Candle wax', nl: 'Kaarsvet', zh: '蜡烛' },
  { type: 'rest', en: 'Cat litter', nl: 'Kattenbakvulling', zh: '猫砂' },
  { type: 'rest', en: 'CD or DVD', nl: 'Cd of dvd', zh: 'CD或DVD' },
  { type: 'rest', en: 'Chewing gum', nl: 'Kauwgom', zh: '口香糖' },
  { type: 'rest', en: 'Chips bag', nl: 'Chipszak', zh: '薯片袋' },
  { type: 'rest', en: 'Cigarette butt', nl: 'Sigarettenpeuk', zh: '烟头' },
  { type: 'rest', en: 'Coffee cup (to-go)', nl: 'Koffiebeker (karton)', zh: '咖啡杯（外带）' },
  { type: 'rest', en: 'Coffee pods (plastic)', nl: 'Koffiecup (plastic)', zh: '咖啡胶囊（塑料）' },
  { type: 'rest', en: 'Contact lens', nl: 'Contactlens', zh: '隐形眼镜' },
  { type: 'rest', en: 'Cork', nl: 'Kurk', zh: '软木塞' },
  { type: 'rest', en: 'Cotton swab', nl: 'Wattenstaafje', zh: '棉签' },
  { type: 'rest', en: 'Diaper', nl: 'Luiers', zh: '尿布' },
  { type: 'rest', en: 'Drinking glass', nl: 'Drinkglas', zh: '饮水杯' },
  { type: 'rest', en: 'Dust', nl: 'Stof', zh: '灰尘' },
  { type: 'rest', en: 'Flower pot (stone)', nl: 'Bloempot (steen)', zh: '花盆（石质）' },
  { type: 'rest', en: 'Light bulb (incandescent)', nl: 'Gloeilamp', zh: '白炽灯泡' },
  { type: 'rest', en: 'Oven dish', nl: 'Ovenschaal', zh: '烤盘' },
  { type: 'rest', en: 'Pen', nl: 'Pen', zh: '笔' },
  { type: 'rest', en: 'Photo', nl: 'Foto', zh: '照片' },
  { type: 'rest', en: 'Pizza box (greasy)', nl: 'Pizzadoos (vettig)', zh: '披萨盒（油腻）' },
  { type: 'rest', en: 'Porcelain', nl: 'Porselein', zh: '瓷器' },
  { type: 'rest', en: 'Receipt', nl: 'Kassabon', zh: '收据' },
  { type: 'rest', en: 'Rubber band', nl: 'Elastiekje', zh: '橡皮筋' },
  { type: 'rest', en: 'Shoes (broken)', nl: 'Schoenen (kapot)', zh: '鞋子（破损）' },
  { type: 'rest', en: 'Sticker', nl: 'Sticker', zh: '贴纸' },
  { type: 'rest', en: 'Styrofoam (food packaging)', nl: 'Piepschuim (voedselverpakking)', zh: '泡沫塑料（食品包装）' },
  { type: 'rest', en: 'Tea glass', nl: 'Theeglas', zh: '茶杯' },
  { type: 'rest', en: 'Toothbrush', nl: 'Tandenborstel', zh: '牙刷' },
  { type: 'rest', en: 'Vacuum cleaner bag', nl: 'Stofzuigerzak', zh: '吸尘器袋' },
  { type: 'rest', en: 'Wallpaper', nl: 'Behang', zh: '墙纸' },

  // Textiles
  { type: 'textiel', en: 'Backpack', nl: 'Rugzak', zh: '背包' },
  { type: 'textiel', en: 'Bedding', nl: 'Beddengoed', zh: '床上用品' },
  { type: 'textiel', en: 'Belt', nl: 'Riem', zh: '皮带' },
  { type: 'textiel', en: 'Clothes (wearable)', nl: 'Kleding (draagbaar)', zh: '衣物（可穿戴）' },
  { type: 'textiel', en: 'Curtains', nl: 'Gordijnen', zh: '窗帘' },
  { type: 'textiel', en: 'Hats', nl: 'Hoeden', zh: '帽子' },
  { type: 'textiel', en: 'Rags', nl: 'Lappen', zh: '抹布' },
  { type: 'textiel', en: 'Shoes (wearable)', nl: 'Schoenen (draagbaar)', zh: '鞋子（可穿戴）' },
  { type: 'textiel', en: 'Soft toys', nl: 'Knuffels', zh: '毛绒玩具' },
  { type: 'textiel', en: 'Towels', nl: 'Handdoeken', zh: '毛巾' },
];

export const SEARCHABLE_WASTE_LIST: SearchableWasteItem[] = wasteList.sort((a, b) => a.en.localeCompare(b.en));