import { GameItem, GlossaryTerm, Language, SearchableWasteItem, WasteType } from './types';

export const LANGUAGES: { id: Language; name: string; flag: string }[] = [
  { id: 'en', name: 'English', flag: '🇬🇧' },
  { id: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { id: 'zh', name: '中文', flag: '🇨🇳' },
];

// All translation keys must be in the 'en' object.
// Other languages will fallback to 'en' if a key is missing.
export const TRANSLATIONS = {
    en: {
        // App
        appTitle: 'Waste Wizard',
        chatTab: 'Chat Wizard',
        gameTab: 'Sort Game',
        infoTab: 'Info & Search',
        footer: 'Waste Wizard © 2024 - Learn to sort waste correctly!',

        // Header
        // (no specific keys here)

        // Chat Agent
        chatIntro: "Hello! I'm the Waste Wizard. Ask me anything about waste separation in the Netherlands, for example: 'Where does a milk carton go?' or 'What are the rules for plastic in Amsterdam?'",
        chatPlaceholder: 'Ask the wizard a question...',
        sources: 'Sources',

        // Game
        gameTitle: 'Waste Sorting Game',
        gameIntro: 'Drag the item to the correct bin!',
        score: 'Score',
        finalScore: 'Final Score',
        playAgain: 'Play Again',
        enterNickname: 'Enter your nickname...',
        saveScore: 'Save Score',
        highScores: 'High Scores',
        gameCorrectBinMessage: 'Correct! This goes in the {binName} bin.',

        // Info & Glossary
        infoTitle: 'Useful Information',
        infoIntro: 'Find more information about waste separation at these official sources.',
        gemeenteContact: 'Your Municipality (Gemeente)',
        gemeenteDesc: 'Rules can differ per city. Always check your local municipality website for the most accurate information.',
        milieuCentraal: 'Milieu Centraal',
        milieuCentraalDesc: 'An independent organization with practical information on sustainability and energy.',
        afvalscheidingswijzer: 'Afvalscheidingswijzer',
        afvalscheidingswijzerDesc: 'The official guide for waste separation in the Netherlands.',
        glossaryTitle: 'Glossary of Waste Types',

        // Waste Search
        wasteSearchTitle: 'What goes where?',
        wasteSearchPlaceholder: 'Search for a waste item...',
        wasteTypeResult: 'Goes in:',

        // Waste Types (for bins and glossary)
        gft: 'VGF (Vegetable, Garden & Fruit)',
        pmd: 'PMD (Plastic, Metal & Drink cartons)',
        rest: 'Residual Waste',
        papier: 'Paper & Cardboard',
        glas: 'Glass',
        kca: 'Small Chemical Waste',
        textiel: 'Textiles',
        'e-waste': 'E-Waste',
        grofvuil: 'Bulky Waste',

        // Waste type definitions (glossary)
        gft_def: 'For all your organic waste like fruit and vegetable scraps, food leftovers, and small garden waste.',
        pmd_def: 'For plastic packaging (bottles, containers), metal packaging (cans), and drink cartons (milk, juice).',
        rest_def: 'For all waste that cannot be separated into other categories, such as diapers or chip bags.',
        papier_def: 'For clean and dry paper and cardboard, like newspapers, boxes, and envelopes.',
        glas_def: 'For empty glass bottles and jars. Lids can often go in PMD. Check local rules.',
        kca_def: 'For hazardous waste like batteries, paint, and energy-saving lamps. Must be returned to a special collection point.',
        textiel_def: 'For wearable clothing, shoes, towels, and home textiles. Should be clean and dry, delivered in a closed bag to a textile container.',
        'e-waste_def': 'For all devices with a plug or battery. Return small devices to stores or bring them to a recycling center (milieustraat).',
        grofvuil_def: 'For large items that do not fit in the regular bin, like furniture. Arrange for collection with your municipality or bring it to a recycling center.',

        // Game items
        apple_core: 'Apple Core',
        plastic_bottle: 'Plastic Bottle',
        pizza_box: 'Greasy Pizza Box',
        newspaper: 'Newspaper',
        wine_bottle: 'Wine Bottle',
        battery: 'Battery',
        banana_peel: 'Banana Peel',
        milk_carton: 'Milk Carton',
        chips_bag: 'Chips Bag',
        cardboard_box: 'Cardboard Box',
        jar_of_jam: 'Jam Jar',
        paint_can: 'Paint Can',
        coffee_grounds: 'Coffee Grounds',
        yoghurt_cup: 'Yoghurt Cup',
        light_bulb: 'Incandescent Bulb',
        magazine: 'Magazine',
        old_tshirt: 'Old T-shirt',
        broken_phone: 'Broken Phone',
    },
    nl: {
        // App
        appTitle: 'Afval Wizard',
        chatTab: 'Chat Wizard',
        gameTab: 'Sorteer Spel',
        infoTab: 'Info & Zoeken',
        footer: 'Afval Wizard © 2024 - Leer afval correct te scheiden!',

        // Chat Agent
        chatIntro: "Hallo! Ik ben de Afval Wizard. Stel me een vraag over afvalscheiding in Nederland, bijvoorbeeld: 'Waar hoort een melkpak?' of 'Wat zijn de regels voor plastic in Amsterdam?'",
        chatPlaceholder: 'Stel de wizard een vraag...',
        sources: 'Bronnen',

        // Game
        gameTitle: 'Afval Sorteer Spel',
        gameIntro: 'Sleep het voorwerp naar de juiste bak!',
        score: 'Score',
        finalScore: 'Eindscore',
        playAgain: 'Opnieuw Spelen',
        enterNickname: 'Voer je bijnaam in...',
        saveScore: 'Score Opslaan',
        highScores: 'Highscores',
        gameCorrectBinMessage: 'Correct! Dit hoort in de {binName} bak.',

        // Info & Glossary
        infoTitle: 'Nuttige Informatie',
        infoIntro: 'Vind meer informatie over afvalscheiding bij deze officiële bronnen.',
        gemeenteContact: 'Jouw Gemeente',
        gemeenteDesc: 'Regels kunnen per stad verschillen. Controleer altijd de website van je lokale gemeente voor de meest accurate informatie.',
        milieuCentraal: 'Milieu Centraal',
        milieuCentraalDesc: 'Een onafhankelijke organisatie met praktische informatie over duurzaamheid en energie.',
        afvalscheidingswijzer: 'Afvalscheidingswijzer',
        afvalscheidingswijzerDesc: 'De officiële gids voor afvalscheiding in Nederland.',
        glossaryTitle: 'Woordenlijst Afvalsoorten',

        // Waste Search
        wasteSearchTitle: 'Wat hoort waar?',
        wasteSearchPlaceholder: 'Zoek naar een afvalproduct...',
        wasteTypeResult: 'Hoort in:',

        // Waste Types
        gft: 'GFT (Groente-, Fruit- en Tuinafval)',
        pmd: 'PMD (Plastic, Metaal & Drankkartons)',
        rest: 'Restafval',
        papier: 'Papier & Karton',
        glas: 'Glas',
        kca: 'Klein Chemisch Afval',
        textiel: 'Textiel',
        'e-waste': 'Elektrisch Afval',
        grofvuil: 'Grofvuil',

        // Waste type definitions
        gft_def: 'Voor al je organisch afval zoals groente- en fruitschillen, etensresten en klein tuinafval.',
        pmd_def: 'Voor plastic verpakkingen (flessen, bakjes), metalen verpakkingen (blikjes) en drankkartons (melk, sap).',
        rest_def: 'Voor al het afval dat niet in andere categorieën kan worden gescheiden, zoals luiers of chipszakken.',
        papier_def: 'Voor schoon en droog papier en karton, zoals kranten, dozen en enveloppen.',
        glas_def: 'Voor lege glazen flessen en potten. Deksels mogen vaak bij PMD. Controleer lokale regels.',
        kca_def: 'Voor gevaarlijk afval zoals batterijen, verf en spaarlampen. Moet worden ingeleverd bij een speciaal inzamelpunt.',
        textiel_def: 'Voor draagbare kleding, schoenen, handdoeken en huishoudtextiel. Moet schoon en droog zijn, aangeleverd in een gesloten zak bij een textielcontainer.',
        'e-waste_def': 'Voor alle apparaten met een stekker of batterij. Lever kleine apparaten in bij winkels of breng ze naar een milieustraat.',
        grofvuil_def: 'Voor grote spullen die niet in de gewone container passen, zoals meubels. Maak een afspraak voor ophaling met je gemeente of breng het naar een milieustraat.',

        // Game items
        apple_core: 'Klokhuis',
        plastic_bottle: 'Plastic Fles',
        pizza_box: 'Vette Pizzadoos',
        newspaper: 'Krant',
        wine_bottle: 'Wijnfles',
        battery: 'Batterij',
        banana_peel: 'Bananenschil',
        milk_carton: 'Melkpak',
        chips_bag: 'Chipszak',
        cardboard_box: 'Kartonnen Doos',
        jar_of_jam: 'Jampot',
        paint_can: 'Verfblik',
        coffee_grounds: 'Koffiedik',
        yoghurt_cup: 'Yoghurtbeker',
        light_bulb: 'Gloeilamp',
        magazine: 'Tijdschrift',
        old_tshirt: 'Oud T-shirt',
        kapotte_telefoon: 'Kapotte Telefoon',
    },
    zh: {
        // App
        appTitle: '垃圾分类精灵',
        chatTab: '聊天精灵',
        gameTab: '分类游戏',
        infoTab: '信息与搜索',
        footer: '垃圾分类精灵 © 2024 - 学习正确分类垃圾！',

        // Chat Agent
        chatIntro: "你好！我是垃圾分类精灵。你可以问我任何关于荷兰垃圾分类的问题，例如：'牛奶盒应该扔在哪里？' 或 '阿姆斯特丹对塑料有什么规定？'",
        chatPlaceholder: '向精灵提问...',
        sources: '来源',

        // Game
        gameTitle: '垃圾分类游戏',
        gameIntro: '将物品拖到正确的垃圾箱！',
        score: '分数',
        finalScore: '最终得分',
        playAgain: '再玩一次',
        enterNickname: '输入你的昵称...',
        saveScore: '保存分数',
        highScores: '高分榜',
        gameCorrectBinMessage: '正确！这应该扔进 {binName} 箱。',

        // Info & Glossary
        infoTitle: '有用信息',
        infoIntro: '在这些官方来源找到更多关于垃圾分类的信息。',
        gemeenteContact: '你所在的市政府 (Gemeente)',
        gemeenteDesc: '不同城市的规定可能不同。请务必查看你当地市政府的网站以获取最准确的信息。',
        milieuCentraal: '中央环境',
        milieuCentraalDesc: '一个提供关于可持续性和能源实用信息的独立组织。',
        afvalscheidingswijzer: '垃圾分类指南',
        afvalscheidingswijzerDesc: '荷兰官方的垃圾分类指南。',
        glossaryTitle: '垃圾类型词汇表',
        
        // Waste Search
        wasteSearchTitle: '什么东西扔哪里？',
        wasteSearchPlaceholder: '搜索垃圾物品...',
        wasteTypeResult: '扔进：',

        // Waste Types
        gft: 'VGF (蔬菜、花园和水果垃圾)',
        pmd: 'PMD (塑料、金属和饮料纸盒)',
        rest: '残余垃圾',
        papier: '纸张和纸板',
        glas: '玻璃',
        kca: '小型化学废物',
        textiel: '纺织品',
        'e-waste': '电子垃圾',
        grofvuil: '大件垃圾',

        // Waste type definitions
        gft_def: '适用于所有有机废物，如水果和蔬菜皮、食物残渣和小型花园废物。',
        pmd_def: '适用于塑料包装（瓶子、容器）、金属包装（罐头）和饮料纸盒（牛奶、果汁）。',
        rest_def: '适用于所有不能分类到其他类别的垃圾，如尿布或薯片袋。',
        papier_def: '适用于清洁干燥的纸张和纸板，如报纸、盒子和信封。',
        glas_def: '适用于空的玻璃瓶和罐子。盖子通常可以放入PMD。请检查当地规定。',
        kca_def: '适用于有害废物，如电池、油漆和节能灯。必须交回特殊收集点。',
        textiel_def: '适用于可穿戴的衣物、鞋子、毛巾和家用纺织品。应保持清洁干燥，并放入封闭的袋子中，投放到纺织品回收箱。',
        'e-waste_def': '适用于所有带插头或电池的设备。将小型设备退回商店或带到回收中心 (milieustraat)。',
        grofvuil_def: '适用于无法放入普通垃圾箱的大件物品，如家具。请与你所在的市政府安排收集，或将其带到回收中心。',

        // Game items
        apple_core: '苹果核',
        plastic_bottle: '塑料瓶',
        pizza_box: '油腻的披萨盒',
        newspaper: '报纸',
        wine_bottle: '酒瓶',
        battery: '电池',
        banana_peel: '香蕉皮',
        milk_carton: '牛奶盒',
        chips_bag: '薯片袋',
        cardboard_box: '纸板箱',
        jar_of_jam: '果酱罐',
        paint_can: '油漆罐',
        coffee_grounds: '咖啡渣',
        yoghurt_cup: '酸奶杯',
        light_bulb: '白炽灯泡',
        magazine: '杂志',
        old_tshirt: '旧T恤',
        broken_phone: '坏掉的手机',
    },
};

export const WASTE_BINS: Record<WasteType, { nameKey: keyof typeof TRANSLATIONS['en']; color: string; }> = {
    gft: { nameKey: 'gft', color: 'bg-green-500' },
    pmd: { nameKey: 'pmd', color: 'bg-orange-400' },
    rest: { nameKey: 'rest', color: 'bg-gray-500' },
    papier: { nameKey: 'papier', color: 'bg-blue-500' },
    glas: { nameKey: 'glas', color: 'bg-yellow-400' },
    kca: { nameKey: 'kca', color: 'bg-red-600' },
    textiel: { nameKey: 'textiel', color: 'bg-purple-500' },
    'e-waste': { nameKey: 'e-waste', color: 'bg-slate-700' },
    grofvuil: { nameKey: 'grofvuil', color: 'bg-amber-800' },
};

export const WASTE_ITEMS: GameItem[] = [
    { nameKey: 'apple_core', image: 'https://i.imgur.com/vL3zQY8.png', type: 'gft' },
    { nameKey: 'plastic_bottle', image: 'https://i.imgur.com/d3aA8Y6.png', type: 'pmd' },
    { nameKey: 'pizza_box', image: 'https://i.imgur.com/uEVvT9H.png', type: 'rest' },
    { nameKey: 'newspaper', image: 'https://i.imgur.com/3Y1ZgQ1.png', type: 'papier' },
    { nameKey: 'wine_bottle', image: 'https://i.imgur.com/4zY4J9p.png', type: 'glas' },
    { nameKey: 'battery', image: 'https://i.imgur.com/9O1yY8T.png', type: 'kca' },
    { nameKey: 'banana_peel', image: 'https://i.imgur.com/J3s0U0S.png', type: 'gft' },
    { nameKey: 'milk_carton', image: 'https://i.imgur.com/Dq8g5g9.png', type: 'pmd' },
    { nameKey: 'chips_bag', image: 'https://i.imgur.com/i8z6o9o.png', type: 'rest' },
    { nameKey: 'cardboard_box', image: 'https://i.imgur.com/mU1gR1j.png', type: 'papier' },
    { nameKey: 'jar_of_jam', image: 'https://i.imgur.com/o3V8aY0.png', type: 'glas' },
    { nameKey: 'paint_can', image: 'https://i.imgur.com/Y1gQ9jT.png', type: 'kca' },
    { nameKey: 'coffee_grounds', image: 'https://i.imgur.com/7b3b8g6.png', type: 'gft' },
    { nameKey: 'yoghurt_cup', image: 'https://i.imgur.com/2Y4bS2s.png', type: 'pmd' },
    { nameKey: 'light_bulb', image: 'https://i.imgur.com/e3g3u4X.png', type: 'rest' },
    { nameKey: 'magazine', image: 'https://i.imgur.com/0u0bV1X.png', type: 'papier' },
    { nameKey: 'old_tshirt', image: 'https://i.imgur.com/Q3H2R9s.png', type: 'textiel' },
    { nameKey: 'broken_phone', image: 'https://i.imgur.com/6U8Y2kY.png', type: 'e-waste' },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
    { termKey: 'gft', definitionKey: 'gft_def' },
    { termKey: 'pmd', definitionKey: 'pmd_def' },
    { termKey: 'rest', definitionKey: 'rest_def' },
    { termKey: 'papier', definitionKey: 'papier_def' },
    { termKey: 'glas', definitionKey: 'glas_def' },
    { termKey: 'kca', definitionKey: 'kca_def' },
    { termKey: 'textiel', definitionKey: 'textiel_def' },
    { termKey: 'e-waste', definitionKey: 'e-waste_def' },
    { termKey: 'grofvuil', definitionKey: 'grofvuil_def' },
];

// Massively expanded list based on afvalscheidingswijzer.nl
const wasteList: SearchableWasteItem[] = [
  { type: 'grofvuil', en: 'Batterijen (en)', nl: 'Batterijen', zh: 'Batterijen (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nPlak knoopcellen en 9 Volt batterijen altijd af met plakband en verpak beschadigde batterijen in huishoudfolie of een plastic zakje. De batterij kan op die manier geen kortsluiting veroorzaken.\n\nMeer over batterijen\n\n!Batterijen' },
  { type: 'e-waste', en: 'Computer (en)', nl: 'Computer', zh: 'Computer (zh)', disposal_info: '## Dit mag in de inleverbak bij diverse winkels. Naar de milieustraat mag ook\n\nIn veel winkels zoals supermarkten, elektronicawinkels en bouwmarkten staan hier inleverbakken voor. Vergeet niet alle (persoonlijke) gegevens en bestanden **te wissen** voordat je je telefoon weggooit.\n\nMeer over apparaten\n\n!Kleine Elektrische Apparaten' },
  { type: 'e-waste', en: 'Elektrisch Apparaat (en)', nl: 'Elektrisch Apparaat', zh: 'Elektrisch Apparaat (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'e-waste', en: 'Elektrische Kabel (en)', nl: 'Elektrische Kabel', zh: 'Elektrische Kabel (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'grofvuil', en: 'Groot Huishoudelijk Apparaat (en)', nl: 'Groot Huishoudelijk Apparaat', zh: 'Groot Huishoudelijk Apparaat (zh)', disposal_info: '## Dit mag terug naar de winkel bij aankoop van een nieuwe, óf naar de milieustraat\n\nLet op: dit inleveradvies is ook van toepassingen als je **online** een nieuw product koopt.' },
  { type: 'rest', en: 'Horloge (en)', nl: 'Horloge', zh: 'Horloge (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Koel Of Vrieskast (en)', nl: 'Koel Of Vrieskast', zh: 'Koel Of Vrieskast (zh)', disposal_info: '## Dit mag terug naar de winkel bij aankoop van een nieuwe, óf naar de milieustraat. Bij het grofvuil mag ook.\n\nLet op: dit inleveradvies is ook van toepassingen als je **online** een nieuw product koopt.\n\nMeer over apparaten' },
  { type: 'grofvuil', en: 'Koelvloeistof Ijsmachine (en)', nl: 'Koelvloeistof Ijsmachine', zh: 'Koelvloeistof Ijsmachine (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'e-waste', en: 'Koolmonoxidemelder (en)', nl: 'Koolmonoxidemelder', zh: 'Koolmonoxidemelder (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'e-waste', en: 'Mobiele Telefoon (en)', nl: 'Mobiele Telefoon', zh: 'Mobiele Telefoon (zh)', disposal_info: '## Dit mag in de inleverbak bij diverse winkels. Naar de milieustraat mag ook\n\nIn veel winkels zoals supermarkten, elektronicawinkels en bouwmarkten staan hier inleverbakken voor. Vergeet niet alle (persoonlijke) gegevens en bestanden **te wissen** voordat je je telefoon weggooit.\n\nMeer over apparaten\n\n!Kleine Elektrische Apparaten' },
  { type: 'rest', en: 'Modem (en)', nl: 'Modem', zh: 'Modem (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Monoblock Warmtepomp Of Airco (en)', nl: 'Monoblock Warmtepomp Of Airco', zh: 'Monoblock Warmtepomp Of Airco (zh)', disposal_info: '## Dit mag terug naar de winkel, óf mee met een installateur bij aankoop van een nieuwe. Naar de milieustraat mag ook\n\n**Let op**: split-unit systemen (airco\'s of warmtepompen) moeten altijd door een gecertificeerd bedrijf worden ontmanteld.\n\nMeer over apparaten' },
  { type: 'rest', en: 'Split Unit Warmtepomp Of Airco (en)', nl: 'Split Unit Warmtepomp Of Airco', zh: 'Split Unit Warmtepomp Of Airco (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Thuisbatterij (en)', nl: 'Thuisbatterij', zh: 'Thuisbatterij (zh)', disposal_info: '## Dit mag naar de milieustraat óf mee met een installateur bij aankoop van een nieuwe.\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Zonnecollector (en)', nl: 'Zonnecollector', zh: 'Zonnecollector (zh)', disposal_info: '## Dit mag naar de milieustraat óf mee met een installateur bij aankoop van een nieuwe.\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Beschermingsmiddel Tegen Virus (en)', nl: 'Beschermingsmiddel Tegen Virus', zh: 'Beschermingsmiddel Tegen Virus (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Chemisch Toiletafval (en)', nl: 'Chemisch Toiletafval', zh: 'Chemisch Toiletafval (zh)', disposal_info: 'None' },
  { type: 'pmd', en: 'Doordrukstrip (en)', nl: 'Doordrukstrip', zh: 'Doordrukstrip (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Handpompje (en)', nl: 'Handpompje', zh: 'Handpompje (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Hygieneproduct (en)', nl: 'Hygieneproduct', zh: 'Hygieneproduct (zh)', disposal_info: '## Dit mag bij het restafval\n\nTenzij je gemeente het gescheiden inzamelt\n\n!Rest' },
  { type: 'rest', en: 'Nagellak (en)', nl: 'Nagellak', zh: 'Nagellak (zh)', disposal_info: '## Dit mag in de glasbak\n\n**Alleen glas waar je doorheen kunt kijken**, hoort in deglasbak. Blauw, groen en rood glas bijvoorbeeld. Glassoorten waar je niet doorheen kunt kijken, gooi je weg bij hetrestafval.\n\nMeer over glas\n\n!Glas' },
  { type: 'rest', en: 'Schoonmaakmiddel Restant (en)', nl: 'Schoonmaakmiddel Restant', zh: 'Schoonmaakmiddel Restant (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Urine (en)', nl: 'Urine', zh: 'Urine (zh)', disposal_info: '## Dit mag je door het toilet spoelen\n\n**Let wel op bij vochtig toiletpapier**. Dit mag i.v.m. verstopping alléén in het toilet als dit op de verpakking wordt aangegeven. Staat het niet op de verpakking? Gooi het dan bij hetrestafval.\n\nMeer over het riool' },
  { type: 'rest', en: 'Verzorgingsproduct (en)', nl: 'Verzorgingsproduct', zh: 'Verzorgingsproduct (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Verzorgingsproduct Vettig (en)', nl: 'Verzorgingsproduct Vettig', zh: 'Verzorgingsproduct Vettig (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Vochtig Wc Papier (en)', nl: 'Vochtig Wc Papier', zh: 'Vochtig Wc Papier (zh)', disposal_info: '## Dit mag je door het toilet spoelen\n\n**Let wel op bij vochtig toiletpapier**. Dit mag i.v.m. verstopping alléén in het toilet als dit op de verpakking wordt aangegeven. Staat het niet op de verpakking? Gooi het dan bij hetrestafval.\n\nMeer over het riool' },
  { type: 'rest', en: 'Cassetteband Of Videoband (en)', nl: 'Cassetteband Of Videoband', zh: 'Cassetteband Of Videoband (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Cd (en)', nl: 'Cd', zh: 'Cd (zh)', disposal_info: '## Dit mag bij het restafval, óf in een speciale inleverbak\n\nCD’s kun je ook inleveren bij speciale inleverbakken, zodat ze gerecycled kunnen worden. Kijk of er eentje bij jou in de buurt is.\n\n!Rest' },
  { type: 'e-waste', en: 'Diskette (en)', nl: 'Diskette', zh: 'Diskette (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'grofvuil', en: 'Doosje Van Cd Of Cassettebandje (en)', nl: 'Doosje Van Cd Of Cassettebandje', zh: 'Doosje Van Cd Of Cassettebandje (zh)', disposal_info: '## Dit mag naar de milieustraat, óf in een speciale inleverbak\n\nJe vindt deze bak vaak in de **supermarkt**, **elektronicawinkel of bouwmarkt**.\n\nAfval scheiden: zin en onzin' },
  { type: 'rest', en: 'Foto En Filmmateriaal (en)', nl: 'Foto En Filmmateriaal', zh: 'Foto En Filmmateriaal (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Langspeelplaat (en)', nl: 'Langspeelplaat', zh: 'Langspeelplaat (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Dierenpoep (en)', nl: 'Dierenpoep', zh: 'Dierenpoep (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Dood Wild Dier (en)', nl: 'Dood Wild Dier', zh: 'Dood Wild Dier (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Kattenbakkorrels (en)', nl: 'Kattenbakkorrels', zh: 'Kattenbakkorrels (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Mest Van Kleine Huisdieren (en)', nl: 'Mest Van Kleine Huisdieren', zh: 'Mest Van Kleine Huisdieren (zh)', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'rest', en: 'Overleden Huisdier (en)', nl: 'Overleden Huisdier', zh: 'Overleden Huisdier (zh)', disposal_info: 'None' },
  { type: 'rest', en: 'Afgestoken Vuurwerk (en)', nl: 'Afgestoken Vuurwerk', zh: 'Afgestoken Vuurwerk (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'kca', en: 'Chemisch Afval (en)', nl: 'Chemisch Afval', zh: 'Chemisch Afval (zh)', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'grofvuil', en: 'Drukhouder (en)', nl: 'Drukhouder', zh: 'Drukhouder (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'gft', en: 'Luchtontvochtigingsvloeistof (en)', nl: 'Luchtontvochtigingsvloeistof', zh: 'Luchtontvochtigingsvloeistof (zh)', disposal_info: '## Dit mag je door de gootsteen spoelen\n\nTwijfel je omdat het afval misschien een verstopping kan veroorzaken? **Kies dan voor gft of restafval**.\n\nMeer over het riool' },
  { type: 'grofvuil', en: 'Ongebruikt Vuurwerk (en)', nl: 'Ongebruikt Vuurwerk', zh: 'Ongebruikt Vuurwerk (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Product Met Klein Explosierisico (en)', nl: 'Product Met Klein Explosierisico', zh: 'Product Met Klein Explosierisico (zh)', disposal_info: '## Dit mag naar de milieustraat óf bij het restafval\n\nGooi het nooit bij de gescheiden inzameling van plastic en metalen vanwege onderdelen met een klein explosierisico.' },
  { type: 'rest', en: 'Radioactieve Producten (en)', nl: 'Radioactieve Producten', zh: 'Radioactieve Producten (zh)', disposal_info: 'None' },
  { type: 'rest', en: 'Spuitbus (en)', nl: 'Spuitbus', zh: 'Spuitbus (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Glas Dat Geen Verpakking Is (en)', nl: 'Glas Dat Geen Verpakking Is', zh: 'Glas Dat Geen Verpakking Is (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Glazen Fles Of Pot (en)', nl: 'Glazen Fles Of Pot', zh: 'Glazen Fles Of Pot (zh)', disposal_info: '## Dit mag in de glasbak\n\n**Alleen glas waar je doorheen kunt kijken**, hoort in deglasbak. Blauw, groen en rood glas bijvoorbeeld. Glassoorten waar je niet doorheen kunt kijken, gooi je weg bij hetrestafval.\n\nMeer over glas\n\n!Glas' },
  { type: 'rest', en: 'Gloei Of Halogeenlamp (en)', nl: 'Gloei Of Halogeenlamp', zh: 'Gloei Of Halogeenlamp (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Spiegel (en)', nl: 'Spiegel', zh: 'Spiegel (zh)', disposal_info: '## Dit mag in een speciale afvalbak voor vlakglas\n\nJe vindt deze bak **bij de milieustraat of bij de glashandel**.' },
  { type: 'e-waste', en: 'Tl Spaar Of Ledlamp (en)', nl: 'Tl Spaar Of Ledlamp', zh: 'Tl Spaar Of Ledlamp (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'rest', en: 'Vaas Van Glas (en)', nl: 'Vaas Van Glas', zh: 'Vaas Van Glas (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Vlakglas (en)', nl: 'Vlakglas', zh: 'Vlakglas (zh)', disposal_info: '## Dit mag in een speciale afvalbak voor vlakglas\n\nJe vindt deze bak **bij de milieustraat of bij de glashandel**.' },
  { type: 'grofvuil', en: 'Geimpregneerd Hout (en)', nl: 'Geimpregneerd Hout', zh: 'Geimpregneerd Hout (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Hout En Houten Plaatmateriaal (en)', nl: 'Hout En Houten Plaatmateriaal', zh: 'Hout En Houten Plaatmateriaal (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'e-waste', en: 'Cartridge (en)', nl: 'Cartridge', zh: 'Cartridge (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'rest', en: 'Ordner (en)', nl: 'Ordner', zh: 'Ordner (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Plakband (en)', nl: 'Plakband', zh: 'Plakband (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Schrijfgerei (en)', nl: 'Schrijfgerei', zh: 'Schrijfgerei (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Aluminiumfolie (en)', nl: 'Aluminiumfolie', zh: 'Aluminiumfolie (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Groente Of Fruitnetje (en)', nl: 'Groente Of Fruitnetje', zh: 'Groente Of Fruitnetje (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Hard Keukenafval (en)', nl: 'Hard Keukenafval', zh: 'Hard Keukenafval (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'rest', en: 'Kaarsvet (en)', nl: 'Kaarsvet', zh: 'Kaarsvet (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Kaaspapier (en)', nl: 'Kaaspapier', zh: 'Kaaspapier (zh)', disposal_info: 'None' },
  { type: 'gft', en: 'Keukenpapier Met Voedselresten (en)', nl: 'Keukenpapier Met Voedselresten', zh: 'Keukenpapier Met Voedselresten (zh)', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'pmd', en: 'Koffiecupje (en)', nl: 'Koffiecupje', zh: 'Koffiecupje (zh)', disposal_info: '## Dit mag naar het inleversysteem van de fabrikant, óf bij het restafval\n\n**Gooi koffiecupjes nooit weg bij het****pmd-afval**. Omdat er koffiedrab in zit, kunnen ze niet als pmd gerecycled worden\n\nMeer over koffie\n\n!Rest' },
  { type: 'gft', en: 'Koffiefilter En Koffiedrab (en)', nl: 'Koffiefilter En Koffiedrab', zh: 'Koffiefilter En Koffiedrab (zh)', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Olie En Vet (en)', nl: 'Olie En Vet', zh: 'Olie En Vet (zh)', disposal_info: '## Dit mag naar de milieustraat, óf naar een speciaal inleverpunt\n\nJe kunt bijvoorbeeld terecht bij verschillende **supermarkten, scholen en sportclubs**.\n\nMeer over olie en vet' },
  { type: 'rest', en: 'Pan (en)', nl: 'Pan', zh: 'Pan (zh)', disposal_info: 'None' },
  { type: 'rest', en: 'Restafval (en)', nl: 'Restafval', zh: 'Restafval (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Schoonmaakdoekjes (en)', nl: 'Schoonmaakdoekjes', zh: 'Schoonmaakdoekjes (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Theezakje En Koffiepad (en)', nl: 'Theezakje En Koffiepad', zh: 'Theezakje En Koffiepad (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Asbesthoudend Afval (en)', nl: 'Asbesthoudend Afval', zh: 'Asbesthoudend Afval (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Behang Wandbedekking (en)', nl: 'Behang Wandbedekking', zh: 'Behang Wandbedekking (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Big Bag (en)', nl: 'Big Bag', zh: 'Big Bag (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Bouwafval (en)', nl: 'Bouwafval', zh: 'Bouwafval (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Dakbedekking Bitumen Teer (en)', nl: 'Dakbedekking Bitumen Teer', zh: 'Dakbedekking Bitumen Teer (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Gereedschap (en)', nl: 'Gereedschap', zh: 'Gereedschap (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Gipsplaat (en)', nl: 'Gipsplaat', zh: 'Gipsplaat (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Kunststof Kozijn (en)', nl: 'Kunststof Kozijn', zh: 'Kunststof Kozijn (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Leeg Verfblik (en)', nl: 'Leeg Verfblik', zh: 'Leeg Verfblik (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Lijm En Kit (en)', nl: 'Lijm En Kit', zh: 'Lijm En Kit (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Puin (en)', nl: 'Puin', zh: 'Puin (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Tape (en)', nl: 'Tape', zh: 'Tape (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'kca', en: 'Verf En Toebehoren (en)', nl: 'Verf En Toebehoren', zh: 'Verf En Toebehoren (zh)', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'grofvuil', en: 'Vinylzeil (en)', nl: 'Vinylzeil', zh: 'Vinylzeil (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Vloerbedekking (en)', nl: 'Vloerbedekking', zh: 'Vloerbedekking (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Coldpack (en)', nl: 'Coldpack', zh: 'Coldpack (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'kca', en: 'Injectienaald (en)', nl: 'Injectienaald', zh: 'Injectienaald (zh)', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'kca', en: 'Medicijn (en)', nl: 'Medicijn', zh: 'Medicijn (zh)', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'rest', en: 'Prothese (en)', nl: 'Prothese', zh: 'Prothese (zh)', disposal_info: 'None' },
  { type: 'rest', en: 'Thuiszorgafval (en)', nl: 'Thuiszorgafval', zh: 'Thuiszorgafval (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Verbandmiddelen (en)', nl: 'Verbandmiddelen', zh: 'Verbandmiddelen (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Ijzer (en)', nl: 'Ijzer', zh: 'Ijzer (zh)', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'rest', en: 'Klein Metalen Voorwerp (en)', nl: 'Klein Metalen Voorwerp', zh: 'Klein Metalen Voorwerp (zh)', disposal_info: '## Dit mag bij het restafval, óf naar de milieustraat\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Magneet (en)', nl: 'Magneet', zh: 'Magneet (zh)', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'pmd', en: 'Metalen Verpakking (en)', nl: 'Metalen Verpakking', zh: 'Metalen Verpakking (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Munten (en)', nl: 'Munten', zh: 'Munten (zh)', disposal_info: '## Dit mag in speciale inleverbakken óf bij het restafval\n\nHet is metaal dus met andere metalen voorwerpen bij de milieustraat mag ook' },
  { type: 'grofvuil', en: 'Oud Ijzer En Andere Metalen (en)', nl: 'Oud Ijzer En Andere Metalen', zh: 'Oud Ijzer En Andere Metalen (zh)', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'rest', en: 'Statiegeldblikje (en)', nl: 'Statiegeldblikje', zh: 'Statiegeldblikje (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Meubels (en)', nl: 'Meubels', zh: 'Meubels (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Afval Van Natuurlijk Materiaal (en)', nl: 'Afval Van Natuurlijk Materiaal', zh: 'Afval Van Natuurlijk Materiaal (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'As Verbrand Materiaal (en)', nl: 'As Verbrand Materiaal', zh: 'As Verbrand Materiaal (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Bedrijfsafval (en)', nl: 'Bedrijfsafval', zh: 'Bedrijfsafval (zh)', disposal_info: 'None' },
  { type: 'rest', en: 'Brita Waterfilter (en)', nl: 'Brita Waterfilter', zh: 'Brita Waterfilter (zh)', disposal_info: '## Dit mag naar het inleversysteem van de fabrikant, óf bij het restafval\n\nWaterfilters van het merk Brita kun je inleveren voor recycling. Is inleveren voor recycling te ingewikkeld? Dan kan het waterfilter bij het restafval.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Gebruiksvoorwerp Niet Recyclebaar (en)', nl: 'Gebruiksvoorwerp Niet Recyclebaar', zh: 'Gebruiksvoorwerp Niet Recyclebaar (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Groot Product Dat Niet In De Kliko Past (en)', nl: 'Groot Product Dat Niet In De Kliko Past', zh: 'Groot Product Dat Niet In De Kliko Past (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Natuurkurk (en)', nl: 'Natuurkurk', zh: 'Natuurkurk (zh)', disposal_info: '## Dit mag in een inleverbak in de winkel, óf bij het restafval\n\nJe kunt over het algemeen terecht bij **iedere winkel waar dit product ook verkocht wordt.**\n\n!Rest' },
  { type: 'rest', en: 'Scherp Voorwerp (en)', nl: 'Scherp Voorwerp', zh: 'Scherp Voorwerp (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Slachtafval (en)', nl: 'Slachtafval', zh: 'Slachtafval (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Bijzonder Papier (en)', nl: 'Bijzonder Papier', zh: 'Bijzonder Papier (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'papier', en: 'Doos Voor Gebak Of Pizza (en)', nl: 'Doos Voor Gebak Of Pizza', zh: 'Doos Voor Gebak Of Pizza (zh)', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'papier', en: 'Papier En Karton (en)', nl: 'Papier En Karton', zh: 'Papier En Karton (zh)', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'papier', en: 'Papier Met Enkelzijdig Plastic Laagje (en)', nl: 'Papier Met Enkelzijdig Plastic Laagje', zh: 'Papier Met Enkelzijdig Plastic Laagje (zh)', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'papier', en: 'Papier Met Waslaagje (en)', nl: 'Papier Met Waslaagje', zh: 'Papier Met Waslaagje (zh)', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'rest', en: 'Papier Niet Schoon Niet Droog (en)', nl: 'Papier Niet Schoon Niet Droog', zh: 'Papier Niet Schoon Niet Droog (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak (en)', nl: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak', zh: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Thermisch Papier (en)', nl: 'Thermisch Papier', zh: 'Thermisch Papier (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Toiletpapier (en)', nl: 'Toiletpapier', zh: 'Toiletpapier (zh)', disposal_info: '## Dit mag je door het toilet spoelen\n\n**Let wel op bij vochtig toiletpapier**. Dit mag i.v.m. verstopping alléén in het toilet als dit op de verpakking wordt aangegeven. Staat het niet op de verpakking? Gooi het dan bij hetrestafval.\n\nMeer over het riool' },
  { type: 'rest', en: 'Verpakking Van Papier Met Plastic Noppenfolie (en)', nl: 'Verpakking Van Papier Met Plastic Noppenfolie', zh: 'Verpakking Van Papier Met Plastic Noppenfolie (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Wegwerpbekertje Karton (en)', nl: 'Wegwerpbekertje Karton', zh: 'Wegwerpbekertje Karton (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Composteerbaar Plastic (en)', nl: 'Composteerbaar Plastic', zh: 'Composteerbaar Plastic (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Drinkpak (en)', nl: 'Drinkpak', zh: 'Drinkpak (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'grofvuil', en: 'Groot Kunststof Afval (en)', nl: 'Groot Kunststof Afval', zh: 'Groot Kunststof Afval (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Grote Plastic Verpakking (en)', nl: 'Grote Plastic Verpakking', zh: 'Grote Plastic Verpakking (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Klein Plastic Verpakkingsonderdeel (en)', nl: 'Klein Plastic Verpakkingsonderdeel', zh: 'Klein Plastic Verpakkingsonderdeel (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Lege Plastic Verpakking Van Chemicalien (en)', nl: 'Lege Plastic Verpakking Van Chemicalien', zh: 'Lege Plastic Verpakking Van Chemicalien (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Lege Plastic Verpakking Van Klein Chemisch Afval (en)', nl: 'Lege Plastic Verpakking Van Klein Chemisch Afval', zh: 'Lege Plastic Verpakking Van Klein Chemisch Afval (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Papier Met Tweezijdig Plasticlaagje (en)', nl: 'Papier Met Tweezijdig Plasticlaagje', zh: 'Papier Met Tweezijdig Plasticlaagje (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Piepschuim (en)', nl: 'Piepschuim', zh: 'Piepschuim (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Piepschuim Schaaltje (en)', nl: 'Piepschuim Schaaltje', zh: 'Piepschuim Schaaltje (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Plastic Bakje Of Kuipje (en)', nl: 'Plastic Bakje Of Kuipje', zh: 'Plastic Bakje Of Kuipje (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Fles (en)', nl: 'Plastic Fles', zh: 'Plastic Fles (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'e-waste', en: 'Plastic Pas Of Kaart (en)', nl: 'Plastic Pas Of Kaart', zh: 'Plastic Pas Of Kaart (zh)', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'pmd', en: 'Plastic Potje (en)', nl: 'Plastic Potje', zh: 'Plastic Potje (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Plastic Product Met Recycling Logo (en)', nl: 'Plastic Product Met Recycling Logo', zh: 'Plastic Product Met Recycling Logo (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Plastic Product Recyclebaar (en)', nl: 'Plastic Product Recyclebaar', zh: 'Plastic Product Recyclebaar (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'pmd', en: 'Plastic Schaaltje (en)', nl: 'Plastic Schaaltje', zh: 'Plastic Schaaltje (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Plastic Statiegeldfles (en)', nl: 'Plastic Statiegeldfles', zh: 'Plastic Statiegeldfles (zh)', disposal_info: 'None' },
  { type: 'pmd', en: 'Plastic Tube (en)', nl: 'Plastic Tube', zh: 'Plastic Tube (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Verpakking (en)', nl: 'Plastic Verpakking', zh: 'Plastic Verpakking (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Verpakking Met Metaallaagje (en)', nl: 'Plastic Verpakking Met Metaallaagje', zh: 'Plastic Verpakking Met Metaallaagje (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Verpakking Van Natuurlijk Materiaal Niet Composteerbaar (en)', nl: 'Plastic Verpakking Van Natuurlijk Materiaal Niet Composteerbaar', zh: 'Plastic Verpakking Van Natuurlijk Materiaal Niet Composteerbaar (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Zakje Afvalzak Of Folie (en)', nl: 'Plastic Zakje Afvalzak Of Folie', zh: 'Plastic Zakje Afvalzak Of Folie (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Zuivelbeker (en)', nl: 'Plastic Zuivelbeker', zh: 'Plastic Zuivelbeker (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Steekschuim (en)', nl: 'Steekschuim', zh: 'Steekschuim (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Servies En Aardewerk (en)', nl: 'Servies En Aardewerk', zh: 'Servies En Aardewerk (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'textiel', en: 'Dekbed En Kussen (en)', nl: 'Dekbed En Kussen', zh: 'Dekbed En Kussen (zh)', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Dons (en)', nl: 'Dons', zh: 'Dons (zh)', disposal_info: '## Dit mag in een inleverbak in de winkel, óf bij het restafval\n\nJe kunt over het algemeen terecht bij **iedere winkel waar dit product ook verkocht wordt.**\n\n!Rest' },
  { type: 'textiel', en: 'Kleding (en)', nl: 'Kleding', zh: 'Kleding (zh)', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Kleding Met Motten (en)', nl: 'Kleding Met Motten', zh: 'Kleding Met Motten (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Matras (en)', nl: 'Matras', zh: 'Matras (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'textiel', en: 'Matrasbeschermer (en)', nl: 'Matrasbeschermer', zh: 'Matrasbeschermer (zh)', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Restanten Stof Kleiner Dan 30X30 Cm (en)', nl: 'Restanten Stof Kleiner Dan 30X30 Cm', zh: 'Restanten Stof Kleiner Dan 30X30 Cm (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'textiel', en: 'Schoenen (en)', nl: 'Schoenen', zh: 'Schoenen (zh)', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Tent Katoen Of Kunststof (en)', nl: 'Tent Katoen Of Kunststof', zh: 'Tent Katoen Of Kunststof (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'textiel', en: 'Textiel (en)', nl: 'Textiel', zh: 'Textiel (zh)', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Textiel Nat Of Vuil (en)', nl: 'Textiel Nat Of Vuil', zh: 'Textiel Nat Of Vuil (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Gemotoriseerd Apparaat (en)', nl: 'Gemotoriseerd Apparaat', zh: 'Gemotoriseerd Apparaat (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'gft', en: 'Giftige Planten (en)', nl: 'Giftige Planten', zh: 'Giftige Planten (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Grof Tuinafval (en)', nl: 'Grof Tuinafval', zh: 'Grof Tuinafval (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'gft', en: 'Grond (en)', nl: 'Grond', zh: 'Grond (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het gft\n\nGaat het om **een beperkte hoeveelheid** groente-, fruit- en tuinafval? Dan kun je het kwijt in de gft-container. Voor veel afval ga je naar de milieustraat.\n\nMeer over de gft-bak\n\n!GFT Etensresten' },
  { type: 'rest', en: 'Hydrokorrels (en)', nl: 'Hydrokorrels', zh: 'Hydrokorrels (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Schadelijk Tuinafval (en)', nl: 'Schadelijk Tuinafval', zh: 'Schadelijk Tuinafval (zh)', disposal_info: '## Dit mag bij het restafval, óf naar de milieustraat\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Tuinafval En Plantenresten (en)', nl: 'Tuinafval En Plantenresten', zh: 'Tuinafval En Plantenresten (zh)', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Tuingereedschap (en)', nl: 'Tuingereedschap', zh: 'Tuingereedschap (zh)', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Wespennest (en)', nl: 'Wespennest', zh: 'Wespennest (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'pmd', en: 'Deksels En Doppen (en)', nl: 'Deksels En Doppen', zh: 'Deksels En Doppen (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken\n\n- ### Waar laat je deksels en doppen?     Klap accordion uit\n\nEen deksel van metaal (ook een bierdopje) mag bij de  gescheiden inzameling  van plastic, metalen en drinkpakken (pmd). Deksels, doppen, etiketten en kurken mogen ook op glazen potten en flessen blijven zitten en mogen mee de  glasbak in.' },
  { type: 'rest', en: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak (en)', nl: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak', zh: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak (zh)', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Plastic Verpakking Met Metaallaagje (en)', nl: 'Plastic Verpakking Met Metaallaagje', zh: 'Plastic Verpakking Met Metaallaagje (zh)', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Volle Verpakking (en)', nl: 'Volle Verpakking', zh: 'Volle Verpakking (zh)', disposal_info: 'None' },
  { type: 'pmd', en: 'Wijnpak (en)', nl: 'Wijnpak', zh: 'Wijnpak (zh)', disposal_info: '## Dit mag in de papierbak én in de bak voor pmd\n\n**Haal eerst** de plastic of aluminium binnenzak uit de doos. Die kan in de pmd-bak (de bak met plastic, metalen en drinkpakken). De kartonnen doos die je overhoudt, kan **daarna** bij het oud papier.\n\nPapierbak\n\n!Papier\n\n!Plastic Blik Drinkpakken' },
  { type: 'gft', en: 'Beslag Restant (en)', nl: 'Beslag Restant', zh: 'Beslag Restant (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Keukenafval (en)', nl: 'Keukenafval', zh: 'Keukenafval (zh)', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Vlees En Visafval (en)', nl: 'Vlees En Visafval', zh: 'Vlees En Visafval (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Vloeibare Voedingsmiddelen (en)', nl: 'Vloeibare Voedingsmiddelen', zh: 'Vloeibare Voedingsmiddelen (zh)', disposal_info: '## Dit mag je door de gootsteen spoelen\n\nTwijfel je omdat het afval misschien een verstopping kan veroorzaken? **Kies dan voor gft of restafval**.\n\nMeer over het riool' },
  { type: 'gft', en: 'Voedselresten (en)', nl: 'Voedselresten', zh: 'Voedselresten (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Zuivel Restant (en)', nl: 'Zuivel Restant', zh: 'Zuivel Restant (zh)', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Aanhangwagen (en)', nl: 'Aanhangwagen', zh: 'Aanhangwagen (zh)', disposal_info: '## Dit mag naar de milieustraat, óf naar een autodemontagebedrijf\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Accu Van Brom Fiets E Scooter Snorfiets (en)', nl: 'Accu Van Brom Fiets E Scooter Snorfiets', zh: 'Accu Van Brom Fiets E Scooter Snorfiets (zh)', disposal_info: '## Dit mag naar de (brom)fietsdealer. Naar de milieustraat mag ook.\n\nDe (brom)fietsdealer waar je de (brom)fiets inlevert, hoeft **niet per se dezelfde te zijn** als waar je de (brom)fiets ook gekocht hebt.\n\nMeer over vervoer' },
  { type: 'rest', en: 'Auto (en)', nl: 'Auto', zh: 'Auto (zh)', disposal_info: '## Dit mag naar een bedrijf dat gespecialiseerd is in demontage van auto\'s\n\nLet er op dat dit bedrijf **aangesloten is bij ARN**. Dit staat voor Auto Recycling Nederland.\n\nMeer over auto onderhoud' },
  { type: 'grofvuil', en: 'Autoaccu (en)', nl: 'Autoaccu', zh: 'Autoaccu (zh)', disposal_info: '## Dit mag naar een autogarage, óf naar de milieustraat\n\nOok kun je naar een ander bedrijf dat **gespecialiseerd is in demontage van auto\'s** gaan.' },
  { type: 'grofvuil', en: 'Autoband (en)', nl: 'Autoband', zh: 'Autoband (zh)', disposal_info: '## Dit mag naar de milieustraat óf naar een dealer bij aankoop van nieuwe banden\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Brandstof En Olie (en)', nl: 'Brandstof En Olie', zh: 'Brandstof En Olie (zh)', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Brom En Snorfiets (en)', nl: 'Brom En Snorfiets', zh: 'Brom En Snorfiets (zh)', disposal_info: '## Dit mag naar de dealer óf naar een recyclingbedrijf\n\nLet erop dat de dealer of het recyclingbedrijf **aangesloten is bij SRN**. Dit staat voor Scooter Recycling Nederland.\n\nMeer over de SRN' },
  { type: 'rest', en: 'Caravan (en)', nl: 'Caravan', zh: 'Caravan (zh)', disposal_info: 'None' },
  { type: 'grofvuil', en: 'Elektrische Fiets (en)', nl: 'Elektrische Fiets', zh: 'Elektrische Fiets (zh)', disposal_info: '## Dit mag terug naar de winkel bij aankoop van een nieuwe, óf naar de milieustraat. Bij het grofvuil mag ook.\n\nLet op: dit inleveradvies is ook van toepassingen als je **online** een nieuw product koopt.\n\nMeer over apparaten' },
  { type: 'grofvuil', en: 'Fiets (en)', nl: 'Fiets', zh: 'Fiets (zh)', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'rest', en: 'Fietsband (en)', nl: 'Fietsband', zh: 'Fietsband (zh)', disposal_info: 'None' },
  { type: 'rest', en: 'Kentekenplaat (en)', nl: 'Kentekenplaat', zh: 'Kentekenplaat (zh)', disposal_info: 'None' },
];

export const SEARCHABLE_WASTE_LIST: SearchableWasteItem[] = wasteList.sort((a, b) => a.en.localeCompare(b.en));