import { GameItem, GlossaryTerm, Language, SearchableWasteItem, WasteType } from './types';

export const LANGUAGES: { id: Language; name: string; flag: string }[] = [
  { id: 'en', name: 'English', flag: '🇬🇧' },
  { id: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { id: 'zh', name: '中文', flag: '🇨🇳' },
];

// All translation keys must be in the 'en' object.
// Other languages will fallback to 'en' if a key is missing.
export const TRANSLATIONS = {
    en: {
        // App
        appTitle: 'Waste Wizard',
        chatTab: 'Chat Wizard',
        gameTab: 'Sort Game',
        infoTab: 'Info & Search',
        footer: 'Waste Wizard © 2024 - Learn to sort waste correctly!',

        // Header
        // (no specific keys here)

        // Chat Agent
        chatIntro: "Hello! I'm the Waste Wizard. Ask me anything about waste separation in the Netherlands, for example: 'Where does a milk carton go?' or 'What are the rules for plastic in Amsterdam?'",
        chatPlaceholder: 'Ask the wizard a question...',
        sources: 'Sources',

        // Game
        gameTitle: 'Waste Sorting Game',
        gameIntro: 'Drag the item to the correct bin!',
        score: 'Score',
        finalScore: 'Final Score',
        playAgain: 'Play Again',
        enterNickname: 'Enter your nickname...',
        saveScore: 'Save Score',
        highScores: 'High Scores',
        gameCorrectBinMessage: 'Correct! This goes in the {binName} bin.',

        // Info & Glossary
        infoTitle: 'Useful Information',
        infoIntro: 'Find more information about waste separation at these official sources.',
        gemeenteContact: 'Your Municipality (Gemeente)',
        gemeenteDesc: 'Rules can differ per city. Always check your local municipality website for the most accurate information.',
        milieuCentraal: 'Milieu Centraal',
        milieuCentraalDesc: 'An independent organization with practical information on sustainability and energy.',
        afvalscheidingswijzer: 'Afvalscheidingswijzer',
        afvalscheidingswijzerDesc: 'The official guide for waste separation in the Netherlands.',
        glossaryTitle: 'Glossary of Waste Types',

        // Waste Search
        wasteSearchTitle: 'What goes where?',
        wasteSearchPlaceholder: 'Search for a waste item...',
        wasteTypeResult: 'Goes in:',

        // Waste Types (for bins and glossary)
        gft: 'VGF (Vegetable, Garden & Fruit)',
        pmd: 'PMD (Plastic, Metal & Drink cartons)',
        rest: 'Residual Waste',
        papier: 'Paper & Cardboard',
        glas: 'Glass',
        kca: 'Small Chemical Waste',
        textiel: 'Textiles',
        'e-waste': 'E-Waste',
        grofvuil: 'Bulky Waste',

        // Waste type definitions (glossary)
        gft_def: 'For all your organic waste like fruit and vegetable scraps, food leftovers, and small garden waste.',
        pmd_def: 'For plastic packaging (bottles, containers), metal packaging (cans), and drink cartons (milk, juice).',
        rest_def: 'For all waste that cannot be separated into other categories, such as diapers or chip bags.',
        papier_def: 'For clean and dry paper and cardboard, like newspapers, boxes, and envelopes.',
        glas_def: 'For empty glass bottles and jars. Lids can often go in PMD. Check local rules.',
        kca_def: 'For hazardous waste like batteries, paint, and energy-saving lamps. Must be returned to a special collection point.',
        textiel_def: 'For wearable clothing, shoes, towels, and home textiles. Should be clean and dry, delivered in a closed bag to a textile container.',
        'e-waste_def': 'For all devices with a plug or battery. Return small devices to stores or bring them to a recycling center (milieustraat).',
        grofvuil_def: 'For large items that do not fit in the regular bin, like furniture. Arrange for collection with your municipality or bring it to a recycling center.',

        // Game items
        apple_core: 'Apple Core',
        plastic_bottle: 'Plastic Bottle',
        pizza_box: 'Greasy Pizza Box',
        newspaper: 'Newspaper',
        wine_bottle: 'Wine Bottle',
        battery: 'Battery',
        banana_peel: 'Banana Peel',
        milk_carton: 'Milk Carton',
        chips_bag: 'Chips Bag',
        cardboard_box: 'Cardboard Box',
        jar_of_jam: 'Jam Jar',
        paint_can: 'Paint Can',
        coffee_grounds: 'Coffee Grounds',
        yoghurt_cup: 'Yoghurt Cup',
        light_bulb: 'Incandescent Bulb',
        magazine: 'Magazine',
        old_tshirt: 'Old T-shirt',
        broken_phone: 'Broken Phone',
    },
    nl: {
        // App
        appTitle: 'Afval Wizard',
        chatTab: 'Chat Wizard',
        gameTab: 'Sorteer Spel',
        infoTab: 'Info & Zoeken',
        footer: 'Afval Wizard © 2024 - Leer afval correct te scheiden!',

        // Chat Agent
        chatIntro: "Hallo! Ik ben de Afval Wizard. Stel me een vraag over afvalscheiding in Nederland, bijvoorbeeld: 'Waar hoort een melkpak?' of 'Wat zijn de regels voor plastic in Amsterdam?'",
        chatPlaceholder: 'Stel de wizard een vraag...',
        sources: 'Bronnen',

        // Game
        gameTitle: 'Afval Sorteer Spel',
        gameIntro: 'Sleep het voorwerp naar de juiste bak!',
        score: 'Score',
        finalScore: 'Eindscore',
        playAgain: 'Opnieuw Spelen',
        enterNickname: 'Voer je bijnaam in...',
        saveScore: 'Score Opslaan',
        highScores: 'Highscores',
        gameCorrectBinMessage: 'Correct! Dit hoort in de {binName} bak.',

        // Info & Glossary
        infoTitle: 'Nuttige Informatie',
        infoIntro: 'Vind meer informatie over afvalscheiding bij deze officiële bronnen.',
        gemeenteContact: 'Jouw Gemeente',
        gemeenteDesc: 'Regels kunnen per stad verschillen. Controleer altijd de website van je lokale gemeente voor de meest accurate informatie.',
        milieuCentraal: 'Milieu Centraal',
        milieuCentraalDesc: 'Een onafhankelijke organisatie met praktische informatie over duurzaamheid en energie.',
        afvalscheidingswijzer: 'Afvalscheidingswijzer',
        afvalscheidingswijzerDesc: 'De officiële gids voor afvalscheiding in Nederland.',
        glossaryTitle: 'Woordenlijst Afvalsoorten',

        // Waste Search
        wasteSearchTitle: 'Wat hoort waar?',
        wasteSearchPlaceholder: 'Zoek naar een afvalproduct...',
        wasteTypeResult: 'Hoort in:',

        // Waste Types
        gft: 'GFT (Groente-, Fruit- en Tuinafval)',
        pmd: 'PMD (Plastic, Metaal & Drankkartons)',
        rest: 'Restafval',
        papier: 'Papier & Karton',
        glas: 'Glas',
        kca: 'Klein Chemisch Afval',
        textiel: 'Textiel',
        'e-waste': 'Elektrisch Afval',
        grofvuil: 'Grofvuil',

        // Waste type definitions
        gft_def: 'Voor al je organisch afval zoals groente- en fruitschillen, etensresten en klein tuinafval.',
        pmd_def: 'Voor plastic verpakkingen (flessen, bakjes), metalen verpakkingen (blikjes) en drankkartons (melk, sap).',
        rest_def: 'Voor al het afval dat niet in andere categorieën kan worden gescheiden, zoals luiers of chipszakken.',
        papier_def: 'Voor schoon en droog papier en karton, zoals kranten, dozen en enveloppen.',
        glas_def: 'Voor lege glazen flessen en potten. Deksels mogen vaak bij PMD. Controleer lokale regels.',
        kca_def: 'Voor gevaarlijk afval zoals batterijen, verf en spaarlampen. Moet worden ingeleverd bij een speciaal inzamelpunt.',
        textiel_def: 'Voor draagbare kleding, schoenen, handdoeken en huishoudtextiel. Moet schoon en droog zijn, aangeleverd in een gesloten zak bij een textielcontainer.',
        'e-waste_def': 'Voor alle apparaten met een stekker of batterij. Lever kleine apparaten in bij winkels of breng ze naar een milieustraat.',
        grofvuil_def: 'Voor grote spullen die niet in de gewone container passen, zoals meubels. Maak een afspraak voor ophaling met je gemeente of breng het naar een milieustraat.',

        // Game items
        apple_core: 'Klokhuis',
        plastic_bottle: 'Plastic Fles',
        pizza_box: 'Vette Pizzadoos',
        newspaper: 'Krant',
        wine_bottle: 'Wijnfles',
        battery: 'Batterij',
        banana_peel: 'Bananenschil',
        milk_carton: 'Melkpak',
        chips_bag: 'Chipszak',
        cardboard_box: 'Kartonnen Doos',
        jar_of_jam: 'Jampot',
        paint_can: 'Verfblik',
        coffee_grounds: 'Koffiedik',
        yoghurt_cup: 'Yoghurtbeker',
        light_bulb: 'Gloeilamp',
        magazine: 'Tijdschrift',
        old_tshirt: 'Oud T-shirt',
        kapotte_telefoon: 'Kapotte Telefoon',
    },
    zh: {
        // App
        appTitle: '垃圾分类精灵',
        chatTab: '聊天精灵',
        gameTab: '分类游戏',
        infoTab: '信息与搜索',
        footer: '垃圾分类精灵 © 2024 - 学习正确分类垃圾！',

        // Chat Agent
        chatIntro: "你好！我是垃圾分类精灵。你可以问我任何关于荷兰垃圾分类的问题，例如：'牛奶盒应该扔在哪里？' 或 '阿姆斯特丹对塑料有什么规定？'",
        chatPlaceholder: '向精灵提问...',
        sources: '来源',

        // Game
        gameTitle: '垃圾分类游戏',
        gameIntro: '将物品拖到正确的垃圾箱！',
        score: '分数',
        finalScore: '最终得分',
        playAgain: '再玩一次',
        enterNickname: '输入你的昵称...',
        saveScore: '保存分数',
        highScores: '高分榜',
        gameCorrectBinMessage: '正确！这应该扔进 {binName} 箱。',

        // Info & Glossary
        infoTitle: '有用信息',
        infoIntro: '在这些官方来源找到更多关于垃圾分类的信息。',
        gemeenteContact: '你所在的市政府 (Gemeente)',
        gemeenteDesc: '不同城市的规定可能不同。请务必查看你当地市政府的网站以获取最准确的信息。',
        milieuCentraal: '中央环境',
        milieuCentraalDesc: '一个提供关于可持续性和能源实用信息的独立组织。',
        afvalscheidingswijzer: '垃圾分类指南',
        afvalscheidingswijzerDesc: '荷兰官方的垃圾分类指南。',
        glossaryTitle: '垃圾类型词汇表',
        
        // Waste Search
        wasteSearchTitle: '什么东西扔哪里？',
        wasteSearchPlaceholder: '搜索垃圾物品...',
        wasteTypeResult: '扔进：',

        // Waste Types
        gft: 'VGF (蔬菜、花园和水果垃圾)',
        pmd: 'PMD (塑料、金属和饮料纸盒)',
        rest: '残余垃圾',
        papier: '纸张和纸板',
        glas: '玻璃',
        kca: '小型化学废物',
        textiel: '纺织品',
        'e-waste': '电子垃圾',
        grofvuil: '大件垃圾',

        // Waste type definitions
        gft_def: '适用于所有有机废物，如水果和蔬菜皮、食物残渣和小型花园废物。',
        pmd_def: '适用于塑料包装（瓶子、容器）、金属包装（罐头）和饮料纸盒（牛奶、果汁）。',
        rest_def: '适用于所有不能分类到其他类别的垃圾，如尿布或薯片袋。',
        papier_def: '适用于清洁干燥的纸张和纸板，如报纸、盒子和信封。',
        glas_def: '适用于空的玻璃瓶和罐子。盖子通常可以放入PMD。请检查当地规定。',
        kca_def: '适用于有害废物，如电池、油漆和节能灯。必须交回特殊收集点。',
        textiel_def: '适用于可穿戴的衣物、鞋子、毛巾和家用纺织品。应保持清洁干燥，并放入封闭的袋子中，投放到纺织品回收箱。',
        'e-waste_def': '适用于所有带插头或电池的设备。将小型设备退回商店或带到回收中心 (milieustraat)。',
        grofvuil_def: '适用于无法放入普通垃圾箱的大件物品，如家具。请与你所在的市政府安排收集，或将其带到回收中心。',

        // Game items
        apple_core: '苹果核',
        plastic_bottle: '塑料瓶',
        pizza_box: '油腻的披萨盒',
        newspaper: '报纸',
        wine_bottle: '酒瓶',
        battery: '电池',
        banana_peel: '香蕉皮',
        milk_carton: '牛奶盒',
        chips_bag: '薯片袋',
        cardboard_box: '纸板箱',
        jar_of_jam: '果酱罐',
        paint_can: '油漆罐',
        coffee_grounds: '咖啡渣',
        yoghurt_cup: '酸奶杯',
        light_bulb: '白炽灯泡',
        magazine: '杂志',
        old_tshirt: '旧T恤',
        broken_phone: '坏掉的手机',
    },
};

export const WASTE_BINS: Record<WasteType, { nameKey: keyof typeof TRANSLATIONS['en']; color: string; }> = {
    gft: { nameKey: 'gft', color: 'bg-green-500' },
    pmd: { nameKey: 'pmd', color: 'bg-orange-400' },
    rest: { nameKey: 'rest', color: 'bg-gray-500' },
    papier: { nameKey: 'papier', color: 'bg-blue-500' },
    glas: { nameKey: 'glas', color: 'bg-yellow-400' },
    kca: { nameKey: 'kca', color: 'bg-red-600' },
    textiel: { nameKey: 'textiel', color: 'bg-purple-500' },
    'e-waste': { nameKey: 'e-waste', color: 'bg-slate-700' },
    grofvuil: { nameKey: 'grofvuil', color: 'bg-amber-800' },
};

export const WASTE_ITEMS: GameItem[] = [
    { nameKey: 'apple_core', image: 'https://i.imgur.com/vL3zQY8.png', type: 'gft' },
    { nameKey: 'plastic_bottle', image: 'https://i.imgur.com/d3aA8Y6.png', type: 'pmd' },
    { nameKey: 'pizza_box', image: 'https://i.imgur.com/uEVvT9H.png', type: 'rest' },
    { nameKey: 'newspaper', image: 'https://i.imgur.com/3Y1ZgQ1.png', type: 'papier' },
    { nameKey: 'wine_bottle', image: 'https://i.imgur.com/4zY4J9p.png', type: 'glas' },
    { nameKey: 'battery', image: 'https://i.imgur.com/9O1yY8T.png', type: 'kca' },
    { nameKey: 'banana_peel', image: 'https://i.imgur.com/J3s0U0S.png', type: 'gft' },
    { nameKey: 'milk_carton', image: 'https://i.imgur.com/Dq8g5g9.png', type: 'pmd' },
    { nameKey: 'chips_bag', image: 'https://i.imgur.com/i8z6o9o.png', type: 'rest' },
    { nameKey: 'cardboard_box', image: 'https://i.imgur.com/mU1gR1j.png', type: 'papier' },
    { nameKey: 'jar_of_jam', image: 'https://i.imgur.com/o3V8aY0.png', type: 'glas' },
    { nameKey: 'paint_can', image: 'https://i.imgur.com/Y1gQ9jT.png', type: 'kca' },
    { nameKey: 'coffee_grounds', image: 'https://i.imgur.com/7b3b8g6.png', type: 'gft' },
    { nameKey: 'yoghurt_cup', image: 'https://i.imgur.com/2Y4bS2s.png', type: 'pmd' },
    { nameKey: 'light_bulb', image: 'https://i.imgur.com/e3g3u4X.png', type: 'rest' },
    { nameKey: 'magazine', image: 'https://i.imgur.com/0u0bV1X.png', type: 'papier' },
    { nameKey: 'old_tshirt', image: 'https://i.imgur.com/Q3H2R9s.png', type: 'textiel' },
    { nameKey: 'broken_phone', image: 'https://i.imgur.com/6U8Y2kY.png', type: 'e-waste' },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
    { termKey: 'gft', definitionKey: 'gft_def' },
    { termKey: 'pmd', definitionKey: 'pmd_def' },
    { termKey: 'rest', definitionKey: 'rest_def' },
    { termKey: 'papier', definitionKey: 'papier_def' },
    { termKey: 'glas', definitionKey: 'glas_def' },
    { termKey: 'kca', definitionKey: 'kca_def' },
    { termKey: 'textiel', definitionKey: 'textiel_def' },
    { termKey: 'e-waste', definitionKey: 'e-waste_def' },
    { termKey: 'grofvuil', definitionKey: 'grofvuil_def' },
];

// Massively expanded list based on afvalscheidingswijzer.nl
const wasteList: SearchableWasteItem[] = [
  { type: 'grofvuil', en: 'Batteries', nl: 'Batterijen', zh: '电池', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nPlak knoopcellen en 9 Volt batterijen altijd af met plakband en verpak beschadigde batterijen in huishoudfolie of een plastic zakje. De batterij kan op die manier geen kortsluiting veroorzaken.\n\nMeer over batterijen\n\n!Batterijen' },
  { type: 'e-waste', en: 'Computer', nl: 'Computer', zh: '电脑', disposal_info: '## Dit mag in de inleverbak bij diverse winkels. Naar de milieustraat mag ook\n\nIn veel winkels zoals supermarkten, elektronicawinkels en bouwmarkten staan hier inleverbakken voor. Vergeet niet alle (persoonlijke) gegevens en bestanden **te wissen** voordat je je telefoon weggooit.\n\nMeer over apparaten\n\n!Kleine Elektrische Apparaten' },
  { type: 'e-waste', en: 'Electrical Appliance', nl: 'Elektrisch Apparaat', zh: '电器', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'e-waste', en: 'Electrical Cable', nl: 'Elektrische Kabel', zh: '电缆', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'grofvuil', en: 'Large Household Appliance', nl: 'Groot Huishoudelijk Apparaat', zh: '大家电', disposal_info: '## Dit mag terug naar de winkel bij aankoop van een nieuwe, óf naar de milieustraat\n\nLet op: dit inleveradvies is ook van toepassingen als je **online** een nieuw product koopt.' },
  { type: 'rest', en: 'Watch', nl: 'Horloge', zh: '手表', disposal_info: null },
  { type: 'grofvuil', en: 'Refrigerator or Freezer', nl: 'Koel Of Vrieskast', zh: '冰箱或冰柜', disposal_info: '## Dit mag terug naar de winkel bij aankoop van een nieuwe, óf naar de milieustraat. Bij het grofvuil mag ook.\n\nLet op: dit inleveradvies is ook van toepassingen als je **online** een nieuw product koopt.\n\nMeer over apparaten' },
  { type: 'grofvuil', en: 'Coolant Ice machine', nl: 'Koelvloeistof Ijsmachine', zh: '冷却液制冰机', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'e-waste', en: 'Carbon monoxide detector', nl: 'Koolmonoxidemelder', zh: '一氧化碳报警器', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'e-waste', en: 'Mobile Phone', nl: 'Mobiele Telefoon', zh: '手机', disposal_info: '## Dit mag in de inleverbak bij diverse winkels. Naar de milieustraat mag ook\n\nIn veel winkels zoals supermarkten, elektronicawinkels en bouwmarkten staan hier inleverbakken voor. Vergeet niet alle (persoonlijke) gegevens en bestanden **te wissen** voordat je je telefoon weggooit.\n\nMeer over apparaten\n\n!Kleine Elektrische Apparaten' },
  { type: 'rest', en: 'Modem', nl: 'Modem', zh: '调制解调器', disposal_info: null },
  { type: 'grofvuil', en: 'Monoblock Heat Pump Or Air Conditioner', nl: 'Monoblock Warmtepomp Of Airco', zh: '一体式热泵或空调', disposal_info: '## Dit mag terug naar de winkel, óf mee met een installateur bij aankoop van een nieuwe. Naar de milieustraat mag ook\n\n**Let op**: split-unit systemen (airco\'s of warmtepompen) moeten altijd door een gecertificeerd bedrijf worden ontmanteld.\n\nMeer over apparaten' },
  { type: 'grofvuil', en: 'Split Unit Heat Pump Or Air Conditioner', nl: 'Split Unit Warmtepomp Of Airco', zh: '分体式热泵或空调', disposal_info: null },
  { type: 'grofvuil', en: 'Home battery', nl: 'Thuisbatterij', zh: '家庭储能电池', disposal_info: '## Dit mag naar de milieustraat óf mee met een installateur bij aankoop van een nieuwe.\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Solar collector', nl: 'Zonnecollector', zh: '太阳能集热器', disposal_info: '## Dit mag naar de milieustraat óf mee met een installateur bij aankoop van een nieuwe.\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Protective Agent Against Virus', nl: 'Beschermingsmiddel Tegen Virus', zh: '抗病毒产品', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Chemical Toilet Waste', nl: 'Chemisch Toiletafval', zh: '化学厕所废物', disposal_info: null },
  { type: 'pmd', en: 'Transfer strip', nl: 'Doordrukstrip', zh: '复写条', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Hand pump', nl: 'Handpompje', zh: '小手泵', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Hygiene product', nl: 'Hygieneproduct', zh: '卫生产品', disposal_info: '## Dit mag bij het restafval\n\nTenzij je gemeente het gescheiden inzamelt\n\n!Rest' },
  { type: 'rest', en: 'Nail polish', nl: 'Nagellak', zh: '指甲油', disposal_info: '## Dit mag in de glasbak\n\n**Alleen glas waar je doorheen kunt kijken**, hoort in deglasbak. Blauw, groen en rood glas bijvoorbeeld. Glassoorten waar je niet doorheen kunt kijken, gooi je weg bij hetrestafval.\n\nMeer over glas\n\n!Glas' },
  { type: 'rest', en: 'Cleaning product residue', nl: 'Schoonmaakmiddel Restant', zh: '清洁剂残留', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Urine', nl: 'Urine', zh: '尿液', disposal_info: '## Dit mag je door het toilet spoelen\n\n**Let wel op bij vochtig toiletpapier**. Dit mag i.v.m. verstopping alléén in het toilet als dit op de verpakking wordt aangegeven. Staat het niet op de verpakking? Gooi het dan bij hetrestafval.\n\nMeer over het riool' },
  { type: 'rest', en: 'Personal care product', nl: 'Verzorgingsproduct', zh: '护理产品', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Oily Personal Care Product', nl: 'Verzorgingsproduct Vettig', zh: '油性护理产品', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Moist toilet paper', nl: 'Vochtig Wc Papier', zh: '湿厕纸', disposal_info: '## Dit mag je door het toilet spoelen\n\n**Let wel op bij vochtig toiletpapier**. Dit mag i.v.m. verstopping alléén in het toilet als dit op de verpakking wordt aangegeven. Staat het niet op de verpakking? Gooi het dan bij hetrestafval.\n\nMeer over het riool' },
  { type: 'rest', en: 'Cassette tape or Videotape', nl: 'Cassetteband Of Videoband', zh: '盒式磁带或录像带', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'CD', nl: 'Cd', zh: '镉', disposal_info: '## Dit mag bij het restafval, óf in een speciale inleverbak\n\nCD’s kun je ook inleveren bij speciale inleverbakken, zodat ze gerecycled kunnen worden. Kijk of er eentje bij jou in de buurt is.\n\n!Rest' },
  { type: 'e-waste', en: 'Floppy disk', nl: 'Diskette', zh: '软盘', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'grofvuil', en: 'CD or cassette case', nl: 'Doosje Van Cd Of Cassettebandje', zh: 'CD盒或磁带盒', disposal_info: '## Dit mag naar de milieustraat, óf in een speciale inleverbak\n\nJe vindt deze bak vaak in de **supermarkt**, **elektronicawinkel of bouwmarkt**.\n\nAfval scheiden: zin en onzin' },
  { type: 'rest', en: 'Photo And Film Material', nl: 'Foto En Filmmateriaal', zh: '影像材料', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Long-playing record', nl: 'Langspeelplaat', zh: '唱片', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Animal poop', nl: 'Dierenpoep', zh: '动物粪便', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Dead Wild Animal', nl: 'Dood Wild Dier', zh: '死亡野生动物', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Cat litter', nl: 'Kattenbakkorrels', zh: '猫砂', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Small Pet Waste', nl: 'Mest Van Kleine Huisdieren', zh: '小型宠物粪便', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'rest', en: 'Deceased Pet', nl: 'Overleden Huisdier', zh: '去世宠物', disposal_info: null },
  { type: 'rest', en: 'Set-off Fireworks', nl: 'Afgestoken Vuurwerk', zh: '燃放的烟花', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'kca', en: 'Chemical Waste', nl: 'Chemisch Afval', zh: '化学废物', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'grofvuil', en: 'Pressure vessel', nl: 'Drukhouder', zh: '压力容器', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'gft', en: 'Dehumidifier liquid', nl: 'Luchtontvochtigingsvloeistof', zh: '除湿液', disposal_info: '## Dit mag je door de gootsteen spoelen\n\nTwijfel je omdat het afval misschien een verstopping kan veroorzaken? **Kies dan voor gft of restafval**.\n\nMeer over het riool' },
  { type: 'grofvuil', en: 'Unused Fireworks', nl: 'Ongebruikt Vuurwerk', zh: '未使用的烟花', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Product With Small Explosion Risk', nl: 'Product Met Klein Explosierisico', zh: '低爆炸风险产品', disposal_info: '## Dit mag naar de milieustraat óf bij het restafval\n\nGooi het nooit bij de gescheiden inzameling van plastic en metalen vanwege onderdelen met een klein explosierisico.' },
  { type: 'rest', en: 'Radioactive Products', nl: 'Radioactieve Producten', zh: '放射性产品', disposal_info: null },
  { type: 'rest', en: 'Aerosol can', nl: 'Spuitbus', zh: '喷雾罐', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Glass That Is Not Packaging', nl: 'Glas Dat Geen Verpakking Is', zh: '非包装玻璃', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Glass Bottle Or Jar', nl: 'Glazen Fles Of Pot', zh: '玻璃瓶或罐子', disposal_info: '## Dit mag in de glasbak\n\n**Alleen glas waar je doorheen kunt kijken**, hoort in deglasbak. Blauw, groen en rood glas bijvoorbeeld. Glassoorten waar je niet doorheen kunt kijken, gooi je weg bij hetrestafval.\n\nMeer over glas\n\n!Glas' },
  { type: 'rest', en: 'Incandescent or Halogen lamp', nl: 'Gloei Of Halogeenlamp', zh: '白炽灯或卤素灯', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Mirror', nl: 'Spiegel', zh: '镜子', disposal_info: '## Dit mag in een speciale afvalbak voor vlakglas\n\nJe vindt deze bak **bij de milieustraat of bij de glashandel**.' },
  { type: 'e-waste', en: 'TL, energy-saving, or LED lamp', nl: 'Tl Spaar Of Ledlamp', zh: '日光灯、节能灯或LED灯', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'rest', en: 'Glass Vase', nl: 'Vaas Van Glas', zh: '玻璃花瓶', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Flat glass', nl: 'Vlakglas', zh: '平板玻璃', disposal_info: '## Dit mag in een speciale afvalbak voor vlakglas\n\nJe vindt deze bak **bij de milieustraat of bij de glashandel**.' },
  { type: 'grofvuil', en: 'Treated Wood', nl: 'Geimpregneerd Hout', zh: '防腐木', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Wood And Wooden Sheet Material', nl: 'Hout En Houten Plaatmateriaal', zh: '木材和木质板材', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'e-waste', en: 'Cartridge', nl: 'Cartridge', zh: '墨盒', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'rest', en: 'Lever arch file', nl: 'Ordner', zh: '活页夹', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Adhesive tape', nl: 'Plakband', zh: '胶带', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Writing implements', nl: 'Schrijfgerei', zh: '文具', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Aluminium foil', nl: 'Aluminiumfolie', zh: '铝箔', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Vegetable Or Fruit Net', nl: 'Groente Of Fruitnetje', zh: '蔬菜或水果网袋', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Hard Kitchen Waste', nl: 'Hard Keukenafval', zh: '硬厨余垃圾', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'rest', en: 'Candle wax', nl: 'Kaarsvet', zh: '蜡烛油', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Cheese paper', nl: 'Kaaspapier', zh: '芝士纸', disposal_info: null },
  { type: 'gft', en: 'Paper Towels With Food Residue', nl: 'Keukenpapier Met Voedselresten', zh: '厨房纸沾有食物残渣', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'pmd', en: 'Coffee pod', nl: 'Koffiecupje', zh: '咖啡胶囊', disposal_info: '## Dit mag naar het inleversysteem van de fabrikant, óf bij het restafval\n\n**Gooi koffiecupjes nooit weg bij het****pmd-afval**. Omdat er koffiedrab in zit, kunnen ze niet als pmd gerecycled worden\n\nMeer over koffie\n\n!Rest' },
  { type: 'gft', en: 'Coffee filter And Coffee grounds', nl: 'Koffiefilter En Koffiedrab', zh: '咖啡过滤器和咖啡渣', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Oil And Fat', nl: 'Olie En Vet', zh: '油脂', disposal_info: '## Dit mag naar de milieustraat, óf naar een speciaal inleverpunt\n\nJe kunt bijvoorbeeld terecht bij verschillende **supermarkten, scholen en sportclubs**.\n\nMeer over olie en vet' },
  { type: 'rest', en: 'Pan', nl: 'Pan', zh: '锅', disposal_info: null },
  { type: 'rest', en: 'Residual waste', nl: 'Restafval', zh: '其他垃圾', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Cleaning wipes', nl: 'Schoonmaakdoekjes', zh: '清洁巾', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Tea Bag And Coffee Pod', nl: 'Theezakje En Koffiepad', zh: '茶包和咖啡包', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Asbestos-containing Waste', nl: 'Asbesthoudend Afval', zh: '含石棉废弃物', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Wallpaper, Wall covering', nl: 'Behang Wandbedekking', zh: '墙纸 墙面装饰', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Big Bag', nl: 'Big Bag', zh: '集装袋', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Construction waste', nl: 'Bouwafval', zh: '建筑垃圾', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Roofing Bitumen Tar', nl: 'Dakbedekking Bitumen Teer', zh: '沥青焦油屋面', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Tools', nl: 'Gereedschap', zh: '工具', disposal_info: null },
  { type: 'grofvuil', en: 'Drywall', nl: 'Gipsplaat', zh: '石膏板', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Plastic Frame', nl: 'Kunststof Kozijn', zh: '塑钢窗框', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Empty Paint Can', nl: 'Leeg Verfblik', zh: '空油漆桶', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Glue And Sealant', nl: 'Lijm En Kit', zh: '胶粘剂和密封胶', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Rubble', nl: 'Puin', zh: '瓦砾', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Tape', nl: 'Tape', zh: '胶带', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'kca', en: 'Paint And Accessories', nl: 'Verf En Toebehoren', zh: '油漆及用品', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'grofvuil', en: 'Vinyl sheet', nl: 'Vinylzeil', zh: '乙烯基地板', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Floor covering', nl: 'Vloerbedekking', zh: '铺地材料', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Cold pack', nl: 'Coldpack', zh: '冰袋', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'kca', en: 'Injection needle', nl: 'Injectienaald', zh: '注射针', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'kca', en: 'Medicine', nl: 'Medicijn', zh: '药', disposal_info: '## Dit mag naar het inleverpunt voor klein chemisch afval\n\nGa daarvoor naar een milieustraat bij jou in de buurt\n\nMeer over klein chemisch afval' },
  { type: 'rest', en: 'Prosthesis', nl: 'Prothese', zh: '假体', disposal_info: null },
  { type: 'rest', en: 'Home care waste', nl: 'Thuiszorgafval', zh: '居家医疗废物', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Medical dressings', nl: 'Verbandmiddelen', zh: '敷料', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Iron', nl: 'Ijzer', zh: '铁', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'rest', en: 'Small Metal Object', nl: 'Klein Metalen Voorwerp', zh: '小金属物体', disposal_info: '## Dit mag bij het restafval, óf naar de milieustraat\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Magnet', nl: 'Magneet', zh: '磁铁', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'pmd', en: 'Metal Packaging', nl: 'Metalen Verpakking', zh: '金属包装', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Coins', nl: 'Munten', zh: '硬币', disposal_info: '## Dit mag in speciale inleverbakken óf bij het restafval\n\nHet is metaal dus met andere metalen voorwerpen bij de milieustraat mag ook' },
  { type: 'grofvuil', en: 'Scrap Iron and Other Metals', nl: 'Oud Ijzer En Andere Metalen', zh: '废铁和其它金属', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'rest', en: 'Deposit can', nl: 'Statiegeldblikje', zh: '押金罐', disposal_info: null },
  { type: 'grofvuil', en: 'Furniture', nl: 'Meubels', zh: '家具', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Waste Of Natural Material', nl: 'Afval Van Natuurlijk Materiaal', zh: '天然材料废弃物', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Burnt Material Ash', nl: 'As Verbrand Materiaal', zh: '焚烧物灰烬', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Commercial waste', nl: 'Bedrijfsafval', zh: '企业废弃物', disposal_info: null },
  { type: 'rest', en: 'Brita Water Filter', nl: 'Brita Waterfilter', zh: '碧然德滤水器', disposal_info: '## Dit mag naar het inleversysteem van de fabrikant, óf bij het restafval\n\nWaterfilters van het merk Brita kun je inleveren voor recycling. Is inleveren voor recycling te ingewikkeld? Dan kan het waterfilter bij het restafval.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Non-Recyclable Item', nl: 'Gebruiksvoorwerp Niet Recyclebaar', zh: '物品不可回收', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Large Product That Doesn\'t Fit In The Wheelie Bin', nl: 'Groot Product Dat Niet In De Kliko Past', zh: '大产品放不进垃圾箱', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Natural cork', nl: 'Natuurkurk', zh: '自然软木', disposal_info: '## Dit mag in een inleverbak in de winkel, óf bij het restafval\n\nJe kunt over het algemeen terecht bij **iedere winkel waar dit product ook verkocht wordt.**\n\n!Rest' },
  { type: 'rest', en: 'Sharp Object', nl: 'Scherp Voorwerp', zh: '尖锐物品', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Offal', nl: 'Slachtafval', zh: '屠宰下脚料', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Special Paper', nl: 'Bijzonder Papier', zh: '特种纸', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'papier', en: 'Box For Pastry Or Pizza', nl: 'Doos Voor Gebak Of Pizza', zh: '糕点或披萨盒', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'papier', en: 'Paper And Cardboard', nl: 'Papier En Karton', zh: '纸和纸板', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'papier', en: 'Paper With Single-sided Plastic Layer', nl: 'Papier Met Enkelzijdig Plastic Laagje', zh: '单面覆塑纸', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'papier', en: 'Paper With Wax Coating', nl: 'Papier Met Waslaagje', zh: '蜡纸', disposal_info: '## Dit mag in de papierbak\n\n**Niet alles van papier kan trouwens in de papierbak**. Foto’s, drinkpakken en behang bijvoorbeeld niet.\n\nMeer over de papierbak\n\n!Papier' },
  { type: 'rest', en: 'Paper Not Clean Not Dry', nl: 'Papier Niet Schoon Niet Droog', zh: '纸不干净不干燥', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Paper Packaging With Plastic And Aluminum Layer No Drink Carton', nl: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak', zh: '纸基塑料铝复合包装，非饮品盒', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Thermal Paper', nl: 'Thermisch Papier', zh: '热敏纸', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Toilet paper', nl: 'Toiletpapier', zh: '卫生纸', disposal_info: '## Dit mag je door het toilet spoelen\n\n**Let wel op bij vochtig toiletpapier**. Dit mag i.v.m. verstopping alléén in het toilet als dit op de verpakking wordt aangegeven. Staat het niet op de verpakking? Gooi het dan bij hetrestafval.\n\nMeer over het riool' },
  { type: 'rest', en: 'Paper Packaging With Plastic Bubble Wrap', nl: 'Verpakking Van Papier Met Plastic Noppenfolie', zh: '纸包装带塑料气泡膜', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Disposable Cup Cardboard', nl: 'Wegwerpbekertje Karton', zh: '一次性纸杯', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Compostable Plastic', nl: 'Composteerbaar Plastic', zh: '可堆肥塑料', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Beverage carton', nl: 'Drinkpak', zh: '饮料盒', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'grofvuil', en: 'Large Plastic Waste', nl: 'Groot Kunststof Afval', zh: '大塑料垃圾', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Large Plastic Packaging', nl: 'Grote Plastic Verpakking', zh: '大型塑料包装', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Small Plastic Packaging Part', nl: 'Klein Plastic Verpakkingsonderdeel', zh: '小塑料包装部件', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Empty Plastic Packaging Of Chemicals', nl: 'Lege Plastic Verpakking Van Chemicalien', zh: '空的塑料化学品包装', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Empty Plastic Packaging of Small Chemical Waste', nl: 'Lege Plastic Verpakking Van Klein Chemisch Afval', zh: '小型化学废弃物空塑料容器', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Paper with a double-sided plastic layer', nl: 'Papier Met Tweezijdig Plasticlaagje', zh: '双面塑料涂层纸', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Styrofoam', nl: 'Piepschuim', zh: '泡沫塑料', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Styrofoam tray', nl: 'Piepschuim Schaaltje', zh: '泡沫塑料托盘', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Plastic Container or Tub', nl: 'Plastic Bakje Of Kuipje', zh: '塑料小盒或小杯', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Bottle', nl: 'Plastic Fles', zh: '塑料瓶', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'e-waste', en: 'Plastic Pass Or Card', nl: 'Plastic Pas Of Kaart', zh: '塑料证件或卡', disposal_info: '## Dit mag in een speciale inleverbak in diverse winkels. Naar de milieustraat mag ook\n\nJe kunt het ook afgeven in de winkel **bij aankoop van een nieuwe**.\n\nMeer over apparaten en elektra\n\n!Kleine Elektrische Apparaten' },
  { type: 'pmd', en: 'Plastic Pot', nl: 'Plastic Potje', zh: '塑料罐', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Plastic Product With Recycling Logo', nl: 'Plastic Product Met Recycling Logo', zh: '带有回收标志的塑料产品', disposal_info: null },
  { type: 'grofvuil', en: 'Plastic Product Recyclable', nl: 'Plastic Product Recyclebaar', zh: '塑料产品可回收', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'pmd', en: 'Plastic Tray', nl: 'Plastic Schaaltje', zh: '塑料盘', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Plastic Deposit Bottle', nl: 'Plastic Statiegeldfles', zh: '塑料押金瓶', disposal_info: null },
  { type: 'pmd', en: 'Plastic Tube', nl: 'Plastic Tube', zh: '塑料管', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Packaging', nl: 'Plastic Verpakking', zh: '塑料包装', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Packaging With A Thin Metal Layer', nl: 'Plastic Verpakking Met Metaallaagje', zh: '镀金属塑料包装', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Packaging Of Natural Material Not Compostable', nl: 'Plastic Verpakking Van Natuurlijk Materiaal Niet Composteerbaar', zh: '天然材料制成的塑料包装不可堆肥', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Bag, Garbage Bag Or Foil', nl: 'Plastic Zakje Afvalzak Of Folie', zh: '塑料袋、垃圾袋或薄膜', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'pmd', en: 'Plastic Dairy Cup', nl: 'Plastic Zuivelbeker', zh: '塑料奶杯', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Floral foam', nl: 'Steekschuim', zh: '花泥', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Dinnerware and Pottery', nl: 'Servies En Aardewerk', zh: '餐具和陶器', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'textiel', en: 'Duvet And Pillow', nl: 'Dekbed En Kussen', zh: '被子和枕头', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Down', nl: 'Dons', zh: '羽绒', disposal_info: '## Dit mag in een inleverbak in de winkel, óf bij het restafval\n\nJe kunt over het algemeen terecht bij **iedere winkel waar dit product ook verkocht wordt.**\n\n!Rest' },
  { type: 'textiel', en: 'Clothing', nl: 'Kleding', zh: '衣服', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Clothing With Moths', nl: 'Kleding Met Motten', zh: '有蛾子的衣服', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Mattress', nl: 'Matras', zh: '床垫', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'textiel', en: 'Mattress protector', nl: 'Matrasbeschermer', zh: '床垫保护套', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Fabric Scraps Smaller Than 30x30 Cm', nl: 'Restanten Stof Kleiner Dan 30X30 Cm', zh: '30x30厘米以下布料边角料', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'textiel', en: 'Shoes', nl: 'Schoenen', zh: '鞋子', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Tent Cotton Or Synthetic', nl: 'Tent Katoen Of Kunststof', zh: '棉或塑料帐篷', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'textiel', en: 'Textile', nl: 'Textiel', zh: '纺织品', disposal_info: '## Dit mag in de textielbak\n\nKleding, textiel en schoenen die nog goed zijn **worden hergebruikt**. Is het niet meer draagbaar of goed te gebruiken? Dan worden de materialen gerecycled.\n\nMeer over kleding, textiel en schoenen\n\n!Kleding Textiel' },
  { type: 'rest', en: 'Textile Wet Or Dirty', nl: 'Textiel Nat Of Vuil', zh: '纺织品湿或脏', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'grofvuil', en: 'Motorized Device', nl: 'Gemotoriseerd Apparaat', zh: '机动装置', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'gft', en: 'Poisonous Plants', nl: 'Giftige Planten', zh: '毒植物', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Bulky garden waste', nl: 'Grof Tuinafval', zh: '粗大园林垃圾', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'gft', en: 'Ground', nl: 'Grond', zh: '土地', disposal_info: '## Dit mag naar de milieustraat, óf bij het gft\n\nGaat het om **een beperkte hoeveelheid** groente-, fruit- en tuinafval? Dan kun je het kwijt in de gft-container. Voor veel afval ga je naar de milieustraat.\n\nMeer over de gft-bak\n\n!GFT Etensresten' },
  { type: 'rest', en: 'Clay pebbles', nl: 'Hydrokorrels', zh: '陶粒', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'rest', en: 'Harmful Garden Waste', nl: 'Schadelijk Tuinafval', zh: '有害园林垃圾', disposal_info: '## Dit mag bij het restafval, óf naar de milieustraat\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'gft', en: 'Garden Waste And Plant Remains', nl: 'Tuinafval En Plantenresten', zh: '园林垃圾和植物残渣', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Garden tools', nl: 'Tuingereedschap', zh: '园艺工具', disposal_info: '## Dit mag naar de milieustraat, óf bij het grofvuil\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'wasp nest', nl: 'Wespennest', zh: '马蜂窝', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'pmd', en: 'Lids And Caps', nl: 'Deksels En Doppen', zh: '盖子和瓶盖', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken\n\n- ### Waar laat je deksels en doppen?     Klap accordion uit\n\nEen deksel van metaal (ook een bierdopje) mag bij de  gescheiden inzameling  van plastic, metalen en drinkpakken (pmd). Deksels, doppen, etiketten en kurken mogen ook op glazen potten en flessen blijven zitten en mogen mee de  glasbak in.' },
  { type: 'rest', en: 'Paper Packaging With Plastic And Aluminium Layer, Not A Drink Carton', nl: 'Papieren Verpakking Met Plastic En Aluminiumlaagje Geen Drinkpak', zh: '含塑料和铝内衬的纸包装，非饮料盒', disposal_info: '## Dit mag bij het restafval\n\n**Al het afval dat je niet gescheiden kunt inleveren**, mag bij het restafval. Het gaat dan om bijvoorbeeld kattenbakvulling, koffiecupjes of een kapot wijnglas.\n\nMeer over restafval\n\n!Rest' },
  { type: 'pmd', en: 'Plastic Packaging With Metal Layer', nl: 'Plastic Verpakking Met Metaallaagje', zh: '金属化塑料包装', disposal_info: '## Dit mag bij het pmd\n\nDat is een aparte bak of zak voor **plastic, metalen en drinkpakken.**\n\nPmd-bak of zak\n\n!Plastic Verpakkingen Blik Drinkpakken' },
  { type: 'rest', en: 'Full Packaging', nl: 'Volle Verpakking', zh: '满包装', disposal_info: null },
  { type: 'pmd', en: 'Wine box', nl: 'Wijnpak', zh: '酒盒', disposal_info: '## Dit mag in de papierbak én in de bak voor pmd\n\n**Haal eerst** de plastic of aluminium binnenzak uit de doos. Die kan in de pmd-bak (de bak met plastic, metalen en drinkpakken). De kartonnen doos die je overhoudt, kan **daarna** bij het oud papier.\n\nPapierbak\n\n!Papier\n\n!Plastic Blik Drinkpakken' },
  { type: 'gft', en: 'Seizure Remainder', nl: 'Beslag Restant', zh: '查封余额', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Kitchen waste', nl: 'Keukenafval', zh: '厨余', disposal_info: '## Dit mag bij het gft, óf op de eigen composthoop\n\nJe kunt hiervoor eenbiologisch afbreekbaar zakje (met Kiemplantlogo ofOK-compostlogo) gebruiken. **Let wel op dat je er geen knoop in legt.** Dat composteert namelijk niet goed.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Meat And Fish Waste', nl: 'Vlees En Visafval', zh: '肉和鱼废料', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Liquid Foods', nl: 'Vloeibare Voedingsmiddelen', zh: '液体食品', disposal_info: '## Dit mag je door de gootsteen spoelen\n\nTwijfel je omdat het afval misschien een verstopping kan veroorzaken? **Kies dan voor gft of restafval**.\n\nMeer over het riool' },
  { type: 'gft', en: 'Food remains', nl: 'Voedselresten', zh: '厨余', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'gft', en: 'Dairy Remnant', nl: 'Zuivel Restant', zh: '乳制品残余', disposal_info: '## Dit mag bij het gft\n\n**Heb je geen biobak** voor gft? Dan kun je dit afval weggooien bij hetrestafval.\n\nGft-bak of groene kliko\n\n!GFT Etensresten' },
  { type: 'grofvuil', en: 'Trailer', nl: 'Aanhangwagen', zh: '拖车', disposal_info: '## Dit mag naar de milieustraat, óf naar een autodemontagebedrijf\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Battery For Moped E-Scooter Light Moped', nl: 'Accu Van Brom Fiets E Scooter Snorfiets', zh: '轻便摩托车、电动踏板车、助力车电池', disposal_info: '## Dit mag naar de (brom)fietsdealer. Naar de milieustraat mag ook.\n\nDe (brom)fietsdealer waar je de (brom)fiets inlevert, hoeft **niet per se dezelfde te zijn** als waar je de (brom)fiets ook gekocht hebt.\n\nMeer over vervoer' },
  { type: 'rest', en: 'Car', nl: 'Auto', zh: '汽车', disposal_info: '## Dit mag naar een bedrijf dat gespecialiseerd is in demontage van auto\'s\n\nLet er op dat dit bedrijf **aangesloten is bij ARN**. Dit staat voor Auto Recycling Nederland.\n\nMeer over auto onderhoud' },
  { type: 'grofvuil', en: 'Car battery', nl: 'Autoaccu', zh: '汽车电瓶', disposal_info: '## Dit mag naar een autogarage, óf naar de milieustraat\n\nOok kun je naar een ander bedrijf dat **gespecialiseerd is in demontage van auto\'s** gaan.' },
  { type: 'grofvuil', en: 'Car tire', nl: 'Autoband', zh: '汽车轮胎', disposal_info: '## Dit mag naar de milieustraat óf naar een dealer bij aankoop van nieuwe banden\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'grofvuil', en: 'Fuel And Oil', nl: 'Brandstof En Olie', zh: '燃料和油', disposal_info: '## Dit mag naar de milieustraat\n\nSoms zijn er aan het gebruik van de milieustraat kosten verbonden. Bekijk **welke milieustraat** voor jou het beste te bereiken is en wat eventuele kosten zijn.\n\nMeer over de milieustraat' },
  { type: 'rest', en: 'Moped and Light Moped', nl: 'Brom En Snorfiets', zh: '轻便摩托车和助力车', disposal_info: '## Dit mag naar de dealer óf naar een recyclingbedrijf\n\nLet erop dat de dealer of het recyclingbedrijf **aangesloten is bij SRN**. Dit staat voor Scooter Recycling Nederland.\n\nMeer over de SRN' },
  { type: 'rest', en: 'Caravan', nl: 'Caravan', zh: '房车', disposal_info: null },
  { type: 'grofvuil', en: 'Electric Bicycle', nl: 'Elektrische Fiets', zh: '电动自行车', disposal_info: '## Dit mag terug naar de winkel bij aankoop van een nieuwe, óf naar de milieustraat. Bij het grofvuil mag ook.\n\nLet op: dit inleveradvies is ook van toepassingen als je **online** een nieuw product koopt.\n\nMeer over apparaten' },
  { type: 'grofvuil', en: 'Bicycle', nl: 'Fiets', zh: '自行车', disposal_info: '## Dit mag naar de milieustraat. Of kies voor de oud ijzerhandel\n\nSoms krijg je nog een vergoeding voor het inleveren van oud metaal.\n\nMeer over blik en ander metaal' },
  { type: 'rest', en: 'Bicycle tire', nl: 'Fietsband', zh: '自行车轮胎', disposal_info: null },
  { type: 'rest', en: 'License plate', nl: 'Kentekenplaat', zh: '车牌', disposal_info: null },
];

export const SEARCHABLE_WASTE_LIST: SearchableWasteItem[] = wasteList.sort((a, b) => a.en.localeCompare(b.en));